import { expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { projectGrok, projectGrokHome, grokAdapter } from "../src/index";
import { expectPortableSemantics, portableProjectionInput } from "./fixtures";

test("grok adapter builds a workspace overlay under the auto-discovered .grok/rules dir", () => {
  const bundle = projectGrok(portableProjectionInput);

  expect(bundle.substrate).toBe("grok");
  // project-scoped `.grok/rules/` IS auto-discovered (walked
  // cwd -> repo root, regardless of trust); the home `~/.grok/rules/`
  // dir is not. Context-only — no hook assets at project scope.
  expect(bundle.files.map((file) => file.path)).toEqual([
    ".grok/rules/soma/README.md",
    ".grok/rules/soma/context.md",
    ".grok/rules/soma/memory-layout.md",
    ".grok/rules/soma/skills.md",
    ".grok/rules/soma/policy.md",
  ]);
  expect(bundle.files.find((file) => file.path.endsWith("README.md"))?.content).toContain("generated by Soma");
  expectPortableSemantics(bundle);
});

test("grok home projection preserves portable semantics and gates the active ISA", () => {
  const home = projectGrokHome(portableProjectionInput, "/tmp/soma-home");

  expect(home.substrate).toBe("grok");
  expectPortableSemantics(home);
  // Fixture carries an active ISA → projected under the skills surface.
  expect(home.files.map((file) => file.path)).toContain("skills/soma/active-isa.md");

  const homeNoIsa = projectGrokHome({ ...portableProjectionInput, activeIsa: undefined }, "/tmp/soma-home");
  expect(homeNoIsa.files.map((file) => file.path)).not.toContain("skills/soma/active-isa.md");
});

test("grok home projection renders the verified discovery surface (entry skill + algorithm skill)", () => {
  const home = projectGrokHome(portableProjectionInput, "/tmp/soma-home");
  const paths = home.files.map((file) => file.path);

  // ~/.grok/skills/<name>/SKILL.md is the auto-loaded home surface.
  expect(paths).toContain("skills/soma/SKILL.md");
  expect(paths).toContain("skills/the-algorithm/SKILL.md");

  const entrySkill = home.files.find((file) => file.path === "skills/soma/SKILL.md")?.content ?? "";
  expect(entrySkill).toStartWith("---\nname: soma\n");
  expect(entrySkill).toContain("Source of truth: /tmp/soma-home");
  expect(entrySkill).toContain("skills/soma/active-isa.md");
  // The skill body carries the portable assistant core for discovery.
  expect(entrySkill).toContain("## Assistant");
  expect(entrySkill).toContain("ISC-PORTABLE-1");

  const algorithmSkill = home.files.find((file) => file.path === "skills/the-algorithm/SKILL.md")?.content ?? "";
  expect(algorithmSkill).toContain("name: the-algorithm");
  expect(algorithmSkill).toContain("## Grok Rendering Contract");
  expect(algorithmSkill).toContain("OBSERVE");
});

// map the Algorithm/ISA onto Grok's native verification gates —
// the seven-phase banner contract plus todo_write + --todo-gate + --check,
// seeded from the active ISA criteria. Grok flags live in the grok adapter
// (DD-4); honest scoping = text + todo list, no Pi widgets.

test("the Grok algorithm skill maps phases onto the native todo + verification gates", () => {
  const home = projectGrokHome(portableProjectionInput, "/tmp/soma-home");
  const skill = home.files.find((file) => file.path === "skills/the-algorithm/SKILL.md")?.content ?? "";

  // Seven-phase banner contract is still present (shared base).
  expect(skill).toContain("OBSERVE");
  expect(skill).toContain("VERIFY");
  // Grok-native gate guidance (verified flags + the documented todo tool).
  expect(skill).toContain("## Grok Verification Gates");
  expect(skill).toContain("todo_write");
  expect(skill).toContain("--todo-gate");
  expect(skill).toContain("--check");
  // Honest scoping: text + todos, explicitly no Pi widgets.
  expect(skill).toContain("Do not claim Pi-style widgets");
});

test("the ISA -> todo seed names the active ISA when one is set", () => {
  const skill =
    projectGrokHome(portableProjectionInput, "/tmp/soma-home").files.find(
      (file) => file.path === "skills/the-algorithm/SKILL.md",
    )?.content ?? "";

  expect(skill).toContain("### ISA -> todo seed");
  // The active ISA's criteria are the todo/checklist seed.
  expect(skill).toContain("portable-context");
  expect(skill).toContain("skills/soma/active-isa.md");
});

test("the ISA -> todo seed falls back to PLAN steps when no active ISA is set", () => {
  const noIsaInput = { ...portableProjectionInput, activeIsa: undefined };
  const skill =
    projectGrokHome(noIsaInput, "/tmp/soma-home").files.find(
      (file) => file.path === "skills/the-algorithm/SKILL.md",
    )?.content ?? "";

  expect(skill).toContain("No active ISA is set");
  expect(skill).toContain("seed the todo list from the PLAN steps");
  expect(skill).not.toContain("portable-context");
});

test("grok home projection ships portable skills through the default substrate rewrite", () => {
  const skillInput = {
    ...portableProjectionInput,
    profile: {
      ...portableProjectionInput.profile,
      skills: [
        {
          name: "ledger-update",
          path: "skills/ledger-update",
          description: "Update a ledger.",
          triggers: ["ledger"],
          files: [
            {
              path: "SKILL.md",
              content: "# Ledger Update\n\nRead ~/.claude/memory/ledger.md before updating.",
            },
          ],
        },
      ],
    },
  };

  const home = projectGrokHome(skillInput, "/tmp/soma-home");
  const projected = home.files.find((file) => file.path === "skills/ledger-update/SKILL.md")?.content ?? "";

  // Default-rewrite branch (deliberate): Claude memory roots land on Soma memory.
  expect(projected).toContain("~/.soma/memory/ledger.md");
  expect(projected).not.toContain("~/.claude/memory/");
});

test("grok adapter exposes context build before execution and stubs run()", async () => {
  await expect(grokAdapter.project(portableProjectionInput)).resolves.toMatchObject({ substrate: "grok" });

  await expect(grokAdapter.run({ id: "task-grok", substrate: "grok", prompt: "run" })).resolves.toMatchObject({
    substrate: "grok",
    status: "failed",
    summary: expect.stringContaining("not implemented"),
  });
});

test("grok adapter detect() reflects ~/.grok presence", async () => {
  const originalUserProfile = process.env.USERPROFILE;
  const originalHome = process.env.HOME;
  const tempHome = mkdtempSync(join(tmpdir(), "soma-grok-detect-"));

  try {
    process.env.USERPROFILE = tempHome;
    process.env.HOME = tempHome;

    expect(await grokAdapter.detect()).toBe(false);

    mkdirSync(join(tempHome, ".grok"), { recursive: true });
    expect(await grokAdapter.detect()).toBe(true);
  } finally {
    if (originalUserProfile === undefined) delete process.env.USERPROFILE;
    else process.env.USERPROFILE = originalUserProfile;
    if (originalHome === undefined) delete process.env.HOME;
    else process.env.HOME = originalHome;
    rmSync(tempHome, { recursive: true, force: true });
  }
});
