import { chmod, mkdir, mkdtemp, readdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { expect, test } from "bun:test";
import { runSomaCli } from "../src/cli";
import {
  ROUTER_CORPUS_REPLY_TAIL_CHARS,
  buildRouterCorpus,
  extractRouterCorpusTranscript,
  routerCorpusPath,
  sampleRouterCorpus,
  type RouterCorpusRow,
} from "../src/router-corpus";

let counter = 0;
const nextId = (): string => `u-${(counter += 1).toString().padStart(4, "0")}`;

function typed(content: unknown, extra: Record<string, unknown> = {}): Record<string, unknown> {
  return { type: "user", uuid: nextId(), entrypoint: "cli", timestamp: "2026-09-28T10:00:00.000Z", message: { role: "user", content }, ...extra };
}

function assistant(...blocks: Record<string, unknown>[]): Record<string, unknown> {
  return { type: "assistant", uuid: nextId(), message: { role: "assistant", content: blocks } };
}

function modeHook(promptUuid: string, label: string): Record<string, unknown> {
  return {
    type: "attachment",
    uuid: nextId(),
    parentUuid: promptUuid,
    attachment: { type: "hook_additional_context", hookEvent: "UserPromptSubmit", content: [`Soma MODE: ${label} (auto).\nClassifier reason: x`] },
  };
}

function queued(prompt: string, attachment: Record<string, unknown>): Record<string, unknown> {
  return { type: "attachment", uuid: nextId(), entrypoint: "cli", attachment: { type: "queued_command", prompt, timestamp: "2026-09-28T10:05:00.000Z", ...attachment } };
}

const jsonl = (entries: Record<string, unknown>[]): string => entries.map((entry) => JSON.stringify(entry)).join("\n") + "\n";

test("keeps typed and human-queued prompts, skips every injected shape with a reason", () => {
  const first = typed("please look at the parser");
  const second = typed("do it");
  const entries = [
    first,
    modeHook(first.uuid as string, "ALGORITHM E1"),
    assistant({ type: "thinking", thinking: "PRIVATE-REASONING" }, { type: "text", text: "I propose changing the parser." }),
    { type: "user", uuid: nextId(), entrypoint: "cli", message: { content: [{ type: "tool_result", content: "ok" }] } },
    assistant({ type: "text", text: "Shall I apply it?" }),
    second,
    modeHook(second.uuid as string, "MINIMAL"),
    typed("<task-notification>\n<task-id>x</task-id>"),
    typed("<command-name>/clear</command-name>"),
    typed("<local-command-stdout>done</local-command-stdout>"),
    typed("<bash-input>ls</bash-input>"),
    typed("Caveat: The messages below were generated by the user while running local commands."),
    typed("[Request interrupted by user]"),
    typed("This session is being continued from a previous conversation that ran out of context."),
    typed("summary text", { isCompactSummary: true }),
    typed("<system-reminder>only a reminder</system-reminder>"),
    typed("<some-hook-output>x</some-hook-output>"),
    typed('Another Claude session sent a message: <teammate-message teammate_id="n1">done</teammate-message>'),
    typed("meta prompt", { isMeta: true }),
    typed("agent chatter", { isSidechain: true }),
    queued("also check the tests", { commandMode: "prompt", origin: { kind: "human" } }),
    queued("<task-notification>x</task-notification>", { commandMode: "task-notification" }),
    queued("peer says hi", { commandMode: "prompt", origin: { kind: "peer" }, isMeta: true }),
  ];

  const { rows, skipped } = extractRouterCorpusTranscript(`${jsonl(entries)}not json\n`, { project: "proj", sessionId: "sess" });

  expect(rows.map((row) => [row.source, row.prompt])).toEqual([
    ["typed", "please look at the parser"],
    ["typed", "do it"],
    ["queued", "also check the tests"],
  ]);
  expect(skipped).toMatchObject({
    "malformed-json": 1,
    "tool-result": 1,
    "task-notification": 1,
    "slash-command": 1,
    "local-command": 1,
    bash: 1,
    caveat: 1,
    interrupt: 1,
    "compact-summary": 2,
    empty: 1,
    "peer-message": 1,
    tagged: 1,
    meta: 1,
    sidechain: 1,
    "queued-non-human": 2,
  });

  const [firstRow, secondRow, queuedRow] = rows;
  expect(firstRow).toMatchObject({ hasPreviousReply: false, previousMode: null, regexAtTime: { mode: "algorithm", effort: "E1" } });
  // The reply tail is the visible text since the previous prompt; thinking never leaks in.
  expect(secondRow.replyTail).toBe("I propose changing the parser.\nShall I apply it?");
  expect(secondRow).toMatchObject({ hasPreviousReply: true, previousMode: "algorithm", regexAtTime: { mode: "minimal" } });
  expect(JSON.stringify(rows)).not.toContain("PRIVATE-REASONING");
  expect(queuedRow).toMatchObject({ source: "queued", previousMode: "minimal", regexAtTime: null, hasPreviousReply: false });
});

test("prompts from headless sessions, or with no entrypoint recorded, are left out", () => {
  const entries = [
    typed("interactive prompt"),
    typed("written by a review bot", { entrypoint: "sdk-cli" }),
    typed("too old to tell", { entrypoint: undefined }),
    queued("bot queued this", { commandMode: "prompt", origin: { kind: "human" } }),
  ];
  (entries[3] as Record<string, unknown>).entrypoint = "sdk-ts";

  const { rows, skipped } = extractRouterCorpusTranscript(jsonl(entries), { project: "p", sessionId: "s" });

  expect(rows.map((row) => row.prompt)).toEqual(["interactive prompt"]);
  expect(skipped["non-interactive"]).toBe(2);
  expect(skipped["no-entrypoint"]).toBe(1);
});

test("finds the mode hook's decision through a chain of other hook attachments", () => {
  const prompt = typed("review the adapter");
  const hookA = { type: "attachment", uuid: nextId(), parentUuid: prompt.uuid, attachment: { type: "hook_success" } };
  const hookB = { type: "attachment", uuid: nextId(), parentUuid: hookA.uuid, attachment: { type: "hook_success" } };
  const mode = { ...modeHook(hookB.uuid as string, "NATIVE"), uuid: nextId() };

  const { rows } = extractRouterCorpusTranscript(jsonl([prompt, hookA, hookB, mode]), { project: "p", sessionId: "s" });

  expect(rows[0].regexAtTime).toEqual({ mode: "native" });
});

test("strips system reminders from a typed prompt and keeps only the reply tail", () => {
  const long = "x".repeat(ROUTER_CORPUS_REPLY_TAIL_CHARS + 50) + "END";
  const entries = [
    assistant({ type: "text", text: long }),
    typed([{ type: "text", text: "real question <system-reminder>injected</system-reminder>" }, { type: "image", source: {} }]),
  ];

  const { rows } = extractRouterCorpusTranscript(jsonl(entries), { project: "p", sessionId: "s" });

  expect(rows).toHaveLength(1);
  expect(rows[0].prompt).toBe("real question");
  expect(rows[0].replyTail).toHaveLength(ROUTER_CORPUS_REPLY_TAIL_CHARS);
  expect(rows[0].replyTail.endsWith("END")).toBe(true);
});

test("a replayed prompt still sets the context the next new prompt is built from", () => {
  const replayed = typed("apply the migration");
  const seen = new Set<string>([replayed.uuid as string]);
  const entries = [
    assistant({ type: "text", text: "old reply before the replayed prompt" }),
    replayed,
    modeHook(replayed.uuid as string, "ALGORITHM E3"),
    assistant({ type: "text", text: "Migration applied." }),
    typed("now update the docs"),
  ];

  const { rows, skipped } = extractRouterCorpusTranscript(jsonl(entries), { project: "p", sessionId: "resumed" }, seen);

  expect(skipped.duplicate).toBe(1);
  expect(rows).toHaveLength(1);
  expect(rows[0]).toMatchObject({
    prompt: "now update the docs",
    replyTail: "Migration applied.",
    previousMode: "algorithm",
    previousEffort: "E3",
  });
});

test("a prompt replayed into a resumed session's transcript is counted once", () => {
  const prompt = typed("fix the flaky test");
  const seen = new Set<string>();
  const original = extractRouterCorpusTranscript(jsonl([prompt]), { project: "p", sessionId: "a" }, seen);
  const resumed = extractRouterCorpusTranscript(jsonl([prompt, typed("and now the docs")]), { project: "p", sessionId: "b" }, seen);

  expect(original.rows).toHaveLength(1);
  expect(resumed.rows.map((row) => row.prompt)).toEqual(["and now the docs"]);
  expect(resumed.skipped.duplicate).toBe(1);
});

test("sampling is deterministic per seed and bounded by the sample size", () => {
  const rows = Array.from({ length: 50 }, (_, index) => ({ id: `id-${index}` }) as RouterCorpusRow);
  const once = sampleRouterCorpus(rows, 10, "seed-a").map((row) => row.id);

  expect(once).toHaveLength(10);
  expect(sampleRouterCorpus(rows, 10, "seed-a").map((row) => row.id)).toEqual(once);
  expect(sampleRouterCorpus(rows, 10, "seed-b").map((row) => row.id)).not.toEqual(once);
  expect(sampleRouterCorpus(rows, 500, "seed-a")).toHaveLength(50);
});

async function withProjects(action: (root: string, projectsDir: string) => Promise<void>): Promise<void> {
  const root = await mkdtemp(join(tmpdir(), "soma-router-corpus-"));
  const projectsDir = join(root, ".claude", "projects");
  try {
    await mkdir(join(projectsDir, "-work-demo", "sess-1", "subagents"), { recursive: true });
    await writeFile(join(projectsDir, "-work-demo", "sess-1.jsonl"), jsonl([typed("typed by the principal"), typed("a second prompt")]));
    await writeFile(join(projectsDir, "-work-demo", "sess-1", "subagents", "agent-1.jsonl"), jsonl([typed("subagent traffic")]));
    await writeFile(join(projectsDir, "-work-demo", "notes.txt"), "not a transcript");
    await action(root, projectsDir);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

test("buildRouterCorpus reads session transcripts and never subagent transcripts", async () => {
  await withProjects(async (_root, projectsDir) => {
    const result = await buildRouterCorpus({ projectsDir });

    expect(result.transcripts).toBe(1);
    expect(result.candidates).toBe(2);
    expect(result.sessions).toBe(1);
    expect(result.rows.map((row) => row.prompt).sort()).toEqual(["a second prompt", "typed by the principal"]);
    expect(result.rows[0]).toMatchObject({ project: "-work-demo", sessionId: "sess-1" });
  });
});

test("soma router corpus writes the private corpus and prints counts, never prompts", async () => {
  await withProjects(async (root, projectsDir) => {
    const somaHome = join(root, ".soma");

    const dry = await runSomaCli(["router", "corpus", "--projects-dir", projectsDir, "--soma-home", somaHome, "--dry-run"]);
    expect(dry).toContain("written: no (dry run)");
    await expect(stat(routerCorpusPath(somaHome))).rejects.toThrow();

    const output = await runSomaCli(["router", "corpus", "--projects-dir", projectsDir, "--soma-home", somaHome, "--sample", "1"]);
    expect(output).toContain("candidate prompts: 2");
    expect(output).toContain("sampled: 1 from 1 session(s)");
    expect(output).not.toContain("typed by the principal");
    expect(output).not.toContain("a second prompt");

    const written = (await readFile(routerCorpusPath(somaHome), "utf8")).trim().split("\n");
    expect(written).toHaveLength(1);
    expect(((await stat(routerCorpusPath(somaHome))).mode & 0o777).toString(8)).toBe("600");

    const json = JSON.parse(await runSomaCli(["router", "corpus", "--projects-dir", projectsDir, "--soma-home", somaHome, "--json"])) as { sampled: number };
    expect(json.sampled).toBe(2);
  });
});

test("an existing world-readable output file ends up owner-only", async () => {
  await withProjects(async (root, projectsDir) => {
    const out = join(root, "corpus.jsonl");
    await writeFile(out, "stale\n", { mode: 0o644 });
    await chmod(out, 0o644);

    await runSomaCli(["router", "corpus", "--projects-dir", projectsDir, "--out", out]);

    expect(((await stat(out)).mode & 0o777).toString(8)).toBe("600");
    expect(await readFile(out, "utf8")).not.toContain("stale");
    expect((await readdir(root)).filter((name) => name.endsWith(".tmp"))).toEqual([]);
  });
});

test("a missing projects directory fails and leaves the existing corpus untouched", async () => {
  await withProjects(async (root) => {
    const out = join(root, "corpus.jsonl");
    await writeFile(out, "existing corpus\n");

    await expect(runSomaCli(["router", "corpus", "--projects-dir", join(root, "typo"), "--out", out])).rejects.toThrow();
    expect(await readFile(out, "utf8")).toBe("existing corpus\n");
  });
});
