import { describe, expect, test } from "bun:test";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { diagnoseSkillStubDrift } from "../src/adapters/skill-stub-doctor";
import { bootstrapSomaHome, diagnoseSomaDoctor } from "../src/index";
import { projectSkill } from "../src/skill-projection";

/**
 * soma#542 — a projected stub is a pointer, so the thing that rots is the
 * pointer. Content-compare cannot see it: a stub aimed at a deleted body still
 * matches its own renderer byte for byte, which is exactly why this check
 * dereferences instead of diffing.
 */

async function withTempHome<T>(fn: (homeDir: string) => Promise<T>): Promise<T> {
  const homeDir = await mkdtemp(join(tmpdir(), "soma-stub-doctor-"));
  try {
    await bootstrapSomaHome({ homeDir });
    return await fn(homeDir);
  } finally {
    await rm(homeDir, { recursive: true, force: true });
  }
}

async function writeSourceSkill(homeDir: string, name: string): Promise<string> {
  const skillDir = join(homeDir, "source", name);
  await mkdir(skillDir, { recursive: true });
  await writeFile(join(skillDir, "SKILL.md"), `---\nname: ${name}\ndescription: "A test skill."\n---\n\n# ${name}\n`, "utf8");
  return skillDir;
}

const piLoader = (homeDir: string, name: string) => join(homeDir, ".pi", "agent", "skills", name);
const registrySlot = (homeDir: string, name: string) => join(homeDir, ".soma", "skills", name);

describe("diagnoseSkillStubDrift", () => {
  test("a freshly projected stub is healthy", async () => {
    await withTempHome(async (homeDir) => {
      await projectSkill({ skillDir: await writeSourceSkill(homeDir, "MyTool"), substrates: ["pi-dev"], homeDir });

      expect(await diagnoseSkillStubDrift({ substrate: "pi-dev", homeDir })).toEqual([]);
    });
  });

  test("reports a stub whose body no longer exists", async () => {
    await withTempHome(async (homeDir) => {
      const skillDir = await writeSourceSkill(homeDir, "MyTool");
      await projectSkill({ skillDir, substrates: ["pi-dev"], homeDir });

      // The registry slot goes away — a rename, or an unproject that did not
      // reach this loader. The stub is untouched and still perfectly formed.
      await rm(registrySlot(homeDir, "MyTool"), { recursive: true, force: true });

      const findings = await diagnoseSkillStubDrift({ substrate: "pi-dev", homeDir });
      expect(findings).toHaveLength(1);
      expect(findings[0]?.id).toBe("skill-stub-dangling");
      expect(findings[0]?.severity).toBe("error");
      expect(findings[0]?.message).toContain("MyTool");
      expect(findings[0]?.action).toContain("project-skill");
    });
  });

  test("names every dangling skill, sorted", async () => {
    await withTempHome(async (homeDir) => {
      for (const name of ["Zeta", "Alpha", "Mid"]) {
        await projectSkill({ skillDir: await writeSourceSkill(homeDir, name), substrates: ["pi-dev"], homeDir });
        await rm(registrySlot(homeDir, name), { recursive: true, force: true });
      }

      const findings = await diagnoseSkillStubDrift({ substrate: "pi-dev", homeDir });
      expect(findings).toHaveLength(1);
      expect(findings[0]?.message).toContain("Alpha, Mid, Zeta");
      expect(findings[0]?.message).toContain("3 projected skill stubs point");
    });
  });

  test("a stub with the marker but no readable pointer is a separate, softer finding", async () => {
    await withTempHome(async (homeDir) => {
      const skillDir = await writeSourceSkill(homeDir, "MyTool");
      await projectSkill({ skillDir, substrates: ["pi-dev"], homeDir });
      // Marker intact, pointer line gone: hand-edited, or an older renderer.
      await writeFile(
        join(piLoader(homeDir, "MyTool"), "SKILL.md"),
        "---\nname: MyTool\n---\n\n<!-- Generated by Soma (soma:skill-stub, soma install pi-dev). -->\n",
        "utf8",
      );

      const findings = await diagnoseSkillStubDrift({ substrate: "pi-dev", homeDir });
      expect(findings).toHaveLength(1);
      expect(findings[0]?.id).toBe("skill-stub-unreadable");
      // We cannot say whether a body exists, so this must not claim it is gone.
      expect(findings[0]?.severity).toBe("warning");
    });
  });

  test("says nothing about an on-demand substrate", async () => {
    await withTempHome(async (homeDir) => {
      const skillDir = await writeSourceSkill(homeDir, "MyTool");
      await projectSkill({ skillDir, substrates: ["claude-code"], homeDir });
      await rm(registrySlot(homeDir, "MyTool"), { recursive: true, force: true });

      // claude-code symlinks bodies; a broken link is not this check's business.
      expect(await diagnoseSkillStubDrift({ substrate: "claude-code", homeDir })).toEqual([]);
    });
  });

  test("an unprojected home is not drift", async () => {
    await withTempHome(async (homeDir) => {
      // No loader dir at all. A fresh home must not read as broken.
      expect(await diagnoseSkillStubDrift({ substrate: "pi-dev", homeDir })).toEqual([]);
    });
  });

  test("ignores loader entries Soma did not stub", async () => {
    await withTempHome(async (homeDir) => {
      // A hand-authored skill living in the same shared loader dir, and the
      // kernel skill, which is projected as a full body rather than a stub.
      for (const name of ["hand-authored", "soma"]) {
        await mkdir(piLoader(homeDir, name), { recursive: true });
        await writeFile(join(piLoader(homeDir, name), "SKILL.md"), `---\nname: ${name}\n---\n\n# ${name}\n`, "utf8");
      }

      expect(await diagnoseSkillStubDrift({ substrate: "pi-dev", homeDir })).toEqual([]);
    });
  });

  test("reports dangling and unreadable together when both are present", async () => {
    await withTempHome(async (homeDir) => {
      await projectSkill({ skillDir: await writeSourceSkill(homeDir, "Gone"), substrates: ["pi-dev"], homeDir });
      await projectSkill({ skillDir: await writeSourceSkill(homeDir, "Broken"), substrates: ["pi-dev"], homeDir });
      await rm(registrySlot(homeDir, "Gone"), { recursive: true, force: true });
      await writeFile(
        join(piLoader(homeDir, "Broken"), "SKILL.md"),
        "---\nname: Broken\n---\n\n<!-- Generated by Soma (soma:skill-stub, soma install pi-dev). -->\n",
        "utf8",
      );

      const findings = await diagnoseSkillStubDrift({ substrate: "pi-dev", homeDir });
      expect(findings.map((finding) => finding.id).sort()).toEqual(["skill-stub-dangling", "skill-stub-unreadable"]);
    });
  });
});

/**
 * The unit tests above prove the check works; they say nothing about whether
 * `soma doctor` runs it. That wiring is the part a refactor silently drops, so
 * it gets its own assertion through the real diagnosis entrypoint.
 */
describe("soma doctor wiring", () => {
  test("surfaces a dangling stub and escalates the diagnosis to error", async () => {
    await withTempHome(async (homeDir) => {
      const skillDir = await writeSourceSkill(homeDir, "MyTool");
      await projectSkill({ skillDir, substrates: ["pi-dev"], homeDir });
      await rm(registrySlot(homeDir, "MyTool"), { recursive: true, force: true });

      const diagnosis = await diagnoseSomaDoctor({ homeDir, substrate: "pi-dev" });

      expect(diagnosis.findings.some((finding) => finding.id === "skill-stub-dangling")).toBe(true);
      // `error` dominates `warning`, so a fresh home carrying unrelated
      // starter-profile warnings still reports error overall.
      expect(diagnosis.status).toBe("error");
    });
  });

  test("a healthy pi-dev projection contributes no stub finding", async () => {
    await withTempHome(async (homeDir) => {
      await projectSkill({ skillDir: await writeSourceSkill(homeDir, "MyTool"), substrates: ["pi-dev"], homeDir });

      const diagnosis = await diagnoseSomaDoctor({ homeDir, substrate: "pi-dev" });

      expect(diagnosis.findings.some((finding) => finding.id.startsWith("skill-stub-"))).toBe(false);
    });
  });
});
