import type { SubstrateId } from "../../types";

/**
 * Shared provenance + overlay primitives for generated substrate projections
 * (soma#370).
 *
 * Every projected file should announce that it is generated, name its source
 * of truth, and carry a one-command refresh instruction. The header is
 * intentionally free of any wall-clock timestamp so that reprojecting twice
 * with unchanged sources produces byte-identical output (the byte-idempotency
 * law relied on by the install tests and by soma#370's doctor drift checks).
 *
 * `soma doctor` uses `hasProvenanceHeader` as the "this file is still a
 * managed projection" signal: a projected file that has lost its header was
 * hand-replaced and should be flagged, not silently overwritten.
 *
 * The overlay markers delimit a hand-maintained region that survives
 * reprojection. Files that support an overlay (e.g. the generated
 * `~/.claude/CLAUDE.md`, soma#368) keep everything between the markers across
 * regeneration; edits outside the markers are unmanaged drift.
 */

/** Stable substring that identifies any Soma-generated projection file. */
export const PROVENANCE_MARKER = "Generated by Soma";

/**
 * Byte-stable provenance header for a generated projection file, rendered as
 * an HTML comment so it stays invisible when the markdown is displayed but is
 * still greppable by the doctor. No timestamp — see module doc.
 */
export function provenanceHeader(substrate: SubstrateId): string {
  return (
    `<!-- ${PROVENANCE_MARKER} (soma install ${substrate}). ` +
    "Source of truth: ~/.soma. " +
    `Do not edit by hand; run \`soma reproject ${substrate}\` to regenerate. ` +
    "This file is not authoritative. -->"
  );
}

/**
 * True when `content` still carries a Soma provenance header.
 *
 * Anchored to the leading HTML comment rather than a bare substring: a file
 * whose header was removed but whose body happens to contain the marker text
 * must NOT read as managed, or the doctor's missing-header drift signal fails
 * open (sage#377).
 */
export function hasProvenanceHeader(content: string): boolean {
  const trimmed = content.trimStart();
  if (!trimmed.startsWith("<!--")) return false;
  const end = trimmed.indexOf("-->");
  return end !== -1 && trimmed.slice(0, end).includes(PROVENANCE_MARKER);
}

/**
 * Remove a leading provenance header (and the blank line after it) if present,
 * returning the bare content. Round-trips with `withProvenance`:
 * `stripProvenance(withProvenance(s, x)) === x` for any `x` that does not
 * itself begin with a header. Used where code must match projected content
 * against its raw renderer output (e.g. the skill-catalog finder).
 */
export function stripProvenance(content: string): string {
  if (!content.startsWith("<!--")) return content;
  const headerEnd = content.indexOf("-->");
  if (headerEnd === -1 || !content.slice(0, headerEnd).includes(PROVENANCE_MARKER)) {
    return content;
  }
  // Remove ONLY the "\n\n" separator that `withProvenance` inserts, so newlines
  // belonging to the original content survive (sage#377: the old `/^\n+/` ate
  // them, breaking the round-trip for content starting with a newline).
  const rest = content.slice(headerEnd + 3);
  return rest.startsWith("\n\n") ? rest.slice(2) : rest.replace(/^\n/, "");
}

/**
 * Prefix `content` with the provenance header for `substrate`. Idempotent:
 * content that already carries a header is returned unchanged so double
 * application cannot stack headers.
 */
export function withProvenance(substrate: SubstrateId, content: string): string {
  if (hasProvenanceHeader(content)) return content;
  return `${provenanceHeader(substrate)}\n\n${content}`;
}

export const OVERLAY_BEGIN = "<!-- soma:overlay:start — hand-maintained; preserved across reprojection -->";
export const OVERLAY_END = "<!-- soma:overlay:end -->";

/**
 * Extract the hand-maintained overlay body from an existing projected file,
 * or null when the file has no overlay block (missing file, or a pre-overlay
 * projection). The returned string is the content *between* the markers with
 * surrounding blank lines trimmed; markers themselves are not included.
 */
export function extractOverlay(existing: string): string | null {
  const start = existing.indexOf(OVERLAY_BEGIN);
  if (start === -1) return null;
  const bodyStart = start + OVERLAY_BEGIN.length;
  const end = existing.indexOf(OVERLAY_END, bodyStart);
  if (end === -1) return null;
  return existing.slice(bodyStart, end).replace(/^\n+/, "").replace(/\n+$/, "");
}

/**
 * Render an overlay block. When `body` is empty a placeholder comment is
 * emitted so the markers are still present (and thus preserved) on the next
 * reprojection.
 */
export function renderOverlay(body: string | null): string {
  const inner = body && body.trim().length > 0
    ? body.trim()
    : "<!-- Add substrate-local notes here. This region is preserved across `soma reproject`. -->";
  return [OVERLAY_BEGIN, "", inner, "", OVERLAY_END].join("\n");
}
