import { stat } from "node:fs/promises";
import { homedir } from "node:os";
import { resolve } from "node:path";
import type { Projection, ProjectionInput, SomaAdapter, SomaTask } from "../types";
import { activeVsaBundleFile, activeVsaProjectionPath } from "../adapter-active-vsa";
import {
  SOMA_POLICY_PROJECTION_HEADING,
  SOMA_SKILLS_HEADING,
  renderAssistantCore,
  renderPolicyProjection,
  renderSkills,
} from "./shared";

export const ANTHROPIC_COWORK_ENTRYPOINT_PATH = "SOMA.md";
export const ANTHROPIC_COWORK_README_PATH = "soma/README.md";
export const ANTHROPIC_COWORK_INSTRUCTIONS_PATH = "soma/instructions.md";
export const ANTHROPIC_COWORK_PROFILE_PATH = "soma/profile.md";
export const ANTHROPIC_COWORK_PURPOSE_PATH = "soma/purpose.md";
export const ANTHROPIC_COWORK_SKILLS_PATH = "soma/skills.md";
export const ANTHROPIC_COWORK_POLICY_PATH = "soma/policy.md";
export const ANTHROPIC_COWORK_MEMORY_SNAPSHOT_PATH = "soma/memory-snapshot.md";
export const ANTHROPIC_COWORK_ACTIVE_VSA_PATH = activeVsaProjectionPath("anthropic-cowork");
export const ANTHROPIC_COWORK_CAPTURE_README_PATH = "capture/README.md";
export const ANTHROPIC_COWORK_DEFAULT_HOME = ".anthropic-cowork";
export const ANTHROPIC_COWORK_SKILLS_ROOT_PATH = "skills";

const COWORK_README_HEADING = "# Soma Anthropic Cowork Projection";
const COWORK_INSTRUCTIONS_HEADING = "# Soma Anthropic Cowork Instructions";
const COWORK_PROFILE_HEADING = "# Soma Profile Projection";
const COWORK_PURPOSE_HEADING = "# Soma Purpose Projection";
const COWORK_MEMORY_SNAPSHOT_HEADING = "# Soma Memory Snapshot";
const COWORK_CAPTURE_HEADING = "# Soma Capture Inbox";
export const ANTHROPIC_COWORK_ACTIVE_VSA_MARKER = "<!-- generated Soma projection for Claude Cowork active VSA -->";

export function isAnthropicCoworkSkillProjectionPath(path: string): boolean {
  const normalized = path.replaceAll("\\", "/");
  return normalized === ANTHROPIC_COWORK_SKILLS_ROOT_PATH
    || normalized.startsWith(`${ANTHROPIC_COWORK_SKILLS_ROOT_PATH}/`);
}

function renderList(items: string[]): string {
  return items.length === 0 ? "- None declared" : items.map((item) => `- ${item}`).join("\n");
}

function renderEntrypoint(input: ProjectionInput): string {
  return [
    "# Soma",
    "",
    "This folder contains a generated Soma projection for Claude Cowork.",
    "",
    `Assistant: ${input.profile.assistant.displayName ?? input.profile.assistant.name}`,
    "",
    "Read `soma/instructions.md` and `soma/memory-snapshot.md` before making durable claims about identity, memory, active work, or prior decisions.",
    "Use `soma/skills.md` for available Soma skills and `soma/policy.md` for policy limits.",
    "Write candidate durable observations into `capture/`; do not claim they are saved to Soma memory unless a separately implemented, policy-checked process later admits them.",
    "",
    "`~/.soma` is authoritative. Do not assume it is mounted in the Cowork session; files in this folder are generated snapshots and may be overwritten by the next Soma install.",
  ].join("\n");
}

function renderReadme(): string {
  return [
    COWORK_README_HEADING,
    "",
    "This directory is generated by Soma as a standalone Claude Cowork projection folder.",
    "",
    "This scaffold packages generated snapshots for manual review and Cowork-facing experiments instead of granting the private Soma home; it does not enforce what folders a principal grants to Cowork. Review `memory-snapshot.md` as projected memory input, not as an independent privacy filter.",
    "",
    "## Files",
    "",
    "- `instructions.md` - assistant identity, purpose, and operating rules",
    "- `profile.md` - assistant and principal profile subset",
    "- `purpose.md` - mission, goals, principles, and commitments",
    "- `skills.md` - discovered Soma skills",
    "- `policy.md` - advisory-only policy projection",
    "- `memory-snapshot.md` - projected memory readback snapshot",
    "- `active-vsa.md` - active VSA when one is set",
    "- `<projection-folder>/capture/` - candidate memory and session notes for later review outside Cowork",
    "",
    "Principal-maintained changes do not belong in generated files because they are overwritten. Put Cowork-authored outputs that should be considered for Soma memory under `<projection-folder>/capture/`.",
  ].join("\n");
}

function renderInstructions(input: ProjectionInput): string {
  return [
    COWORK_INSTRUCTIONS_HEADING,
    "",
    "You are running inside Claude Cowork with Soma-projected assistant context.",
    "Treat Soma as the portable source of truth. Treat this standalone projection bundle as a generated snapshot, not as the private Soma home.",
    "",
    renderAssistantCore(input),
    "",
    "## Operating Rules",
    "- Read `soma/memory-snapshot.md` before making durable memory claims.",
    "- Use the active VSA as the verification contract when present.",
    "- Treat policy in `soma/policy.md` as advisory because Cowork exposes no verified hook surface.",
    "- Do not claim to have written Soma memory from inside Cowork; write candidate notes to `<projection-folder>/capture/` for later policy-checked review outside Cowork.",
    "- Do not invent local machine paths or assume `~/.soma` is mounted in the Cowork environment.",
  ].join("\n");
}

function renderPurpose(input: ProjectionInput): string {
  const purpose = input.profile.purpose;
  return [
    COWORK_PURPOSE_HEADING,
    "",
    purpose.mission ? `## Mission\n\n${purpose.mission}` : "## Mission\n\nNone declared.",
    "",
    "## Goals",
    "",
    renderList(purpose.goals),
    "",
    "## Principles",
    "",
    renderList(purpose.principles),
    "",
    "## Commitments",
    "",
    renderList(purpose.commitments),
  ].join("\n");
}

function renderPolicy(): string {
  return renderPolicyProjection(
    "anthropic-cowork",
    [],
    [
      "Prompt-level behavior constraints",
      "Verification reporting",
      "Policy inspection before capture ingestion outside Cowork",
      "Organization-managed Cowork controls outside Soma",
    ],
  );
}

function renderMemorySnapshot(input: ProjectionInput): string {
  const index = input.memory?.indexContent;
  return [
    COWORK_MEMORY_SNAPSHOT_HEADING,
    "",
    "This is a generated memory readback for Claude Cowork.",
    "",
    "Do not assume Cowork can read the private Soma home. This file renders the memory index projection input verbatim when that input is available; it is not an independent privacy filter.",
    "",
    "## INDEX-Admitted Memory",
    "",
    index?.trim().length ? index : "No INDEX-admitted memory was available at projection time.",
  ].join("\n");
}

function renderProfile(input: ProjectionInput): string {
  return [COWORK_PROFILE_HEADING, "", renderAssistantCore(input)].join("\n");
}

function renderCaptureReadme(): string {
  return [
    COWORK_CAPTURE_HEADING,
    "",
    "Write candidate durable observations, decisions, and session digests here as Markdown files.",
    "",
    "These files are candidate input only. Review them manually before moving anything into Soma memory unless a separately implemented, policy-checked process later admits them.",
    "",
    "Do not store credentials, private relationship notes, raw enterprise documents, or unrelated working files in this inbox.",
  ].join("\n");
}

type CoworkHomeFileMarkerMatch = "includes" | "startsWith";

interface CoworkStaticHomeFileDescriptor {
  path: string;
  render(input: ProjectionInput): string;
  marker: {
    text: string;
    match: CoworkHomeFileMarkerMatch;
  };
}

const ANTHROPIC_COWORK_STATIC_HOME_FILE_DESCRIPTORS = [
  {
    path: ANTHROPIC_COWORK_ENTRYPOINT_PATH,
    render: renderEntrypoint,
    marker: { text: "generated Soma projection for Claude Cowork", match: "includes" },
  },
  {
    path: ANTHROPIC_COWORK_README_PATH,
    render: () => renderReadme(),
    marker: { text: COWORK_README_HEADING, match: "startsWith" },
  },
  {
    path: ANTHROPIC_COWORK_INSTRUCTIONS_PATH,
    render: renderInstructions,
    marker: { text: COWORK_INSTRUCTIONS_HEADING, match: "startsWith" },
  },
  {
    path: ANTHROPIC_COWORK_PROFILE_PATH,
    render: renderProfile,
    marker: { text: COWORK_PROFILE_HEADING, match: "startsWith" },
  },
  {
    path: ANTHROPIC_COWORK_PURPOSE_PATH,
    render: renderPurpose,
    marker: { text: COWORK_PURPOSE_HEADING, match: "startsWith" },
  },
  {
    path: ANTHROPIC_COWORK_SKILLS_PATH,
    render: renderSkills,
    marker: { text: SOMA_SKILLS_HEADING, match: "startsWith" },
  },
  {
    path: ANTHROPIC_COWORK_POLICY_PATH,
    render: () => renderPolicy(),
    marker: { text: SOMA_POLICY_PROJECTION_HEADING, match: "startsWith" },
  },
  {
    path: ANTHROPIC_COWORK_MEMORY_SNAPSHOT_PATH,
    render: renderMemorySnapshot,
    marker: { text: COWORK_MEMORY_SNAPSHOT_HEADING, match: "startsWith" },
  },
  {
    path: ANTHROPIC_COWORK_CAPTURE_README_PATH,
    render: () => renderCaptureReadme(),
    marker: { text: COWORK_CAPTURE_HEADING, match: "startsWith" },
  },
] satisfies readonly CoworkStaticHomeFileDescriptor[];

export const ANTHROPIC_COWORK_HOME_FILE_PATHS: readonly string[] = [
  ...ANTHROPIC_COWORK_STATIC_HOME_FILE_DESCRIPTORS.map((file) => file.path),
];

export const ANTHROPIC_COWORK_GENERATED_HOME_FILE_MARKERS = ANTHROPIC_COWORK_STATIC_HOME_FILE_DESCRIPTORS.map((file) => ({
  path: file.path,
  marker: file.marker.text,
  markerMatch: file.marker.match,
}));

export function projectAnthropicCoworkHome(input: ProjectionInput): Projection {
  const instructions = renderInstructions(input);
  const activeVsaFiles = activeVsaBundleFile("anthropic-cowork", input.activeVsa).map((file) => ({
    ...file,
    content: [ANTHROPIC_COWORK_ACTIVE_VSA_MARKER, file.content].join("\n"),
  }));
  return {
    substrate: "anthropic-cowork",
    instructions,
    files: [
      ...ANTHROPIC_COWORK_STATIC_HOME_FILE_DESCRIPTORS.map((file) => ({
        path: file.path,
        content: file.path === ANTHROPIC_COWORK_INSTRUCTIONS_PATH ? instructions : file.render(input),
      })),
      ...activeVsaFiles,
    ],
  };
}

export const anthropicCoworkAdapter: SomaAdapter = {
  name: "anthropic-cowork",
  async detect() {
    try {
      const found = await stat(resolve(homedir(), ".anthropic-cowork"));
      return found.isDirectory();
    } catch {
      return false;
    }
  },
  project(input) {
    return Promise.resolve(projectAnthropicCoworkHome(input));
  },
  run(task: SomaTask) {
    return Promise.resolve({
      taskId: task.id,
      substrate: "anthropic-cowork",
      status: "failed",
      summary: "Anthropic Cowork execution is not implemented; use install/export to generate a standalone projection folder.",
    });
  },
};
