import { resolve } from "node:path";
import type { SomaAdapter, Projection, ProjectionInput, SomaTask } from "../types";
import { activeVsaBundleFile } from "../adapter-active-vsa";
import { buildPortableSkillFiles, renderAssistantCore, renderMemoryLayout, renderPolicyProjection, renderSkills, withProvenance } from "./shared";

export const CURSOR_RULES_PATH = ".cursorrules";
export const CURSOR_RULES_BLOCK_BEGIN = "<!-- SOMA_CURSOR_BEGIN -->";
export const CURSOR_RULES_BLOCK_END = "<!-- SOMA_CURSOR_END -->";
export const CURSOR_RULES_README_PATH = ".cursor/rules/soma/README.md";
export const CURSOR_CONTEXT_PATH = ".cursor/rules/soma/CONTEXT.md";
export const CURSOR_PROFILE_PATH = ".cursor/rules/soma/PROFILE.md";
export const CURSOR_PURPOSE_PATH = ".cursor/rules/soma/PURPOSE.md";
export const CURSOR_MEMORY_LAYOUT_PATH = ".cursor/rules/soma/MEMORY_LAYOUT.md";
export const CURSOR_SKILLS_PATH = ".cursor/rules/soma/SKILLS.md";
export const CURSOR_POLICY_PATH = ".cursor/rules/soma/POLICY.md";
export const CURSOR_MCP_PATH = ".cursor/rules/soma/MCP.md";
// Portable bundled skills land under the Soma-owned Cursor skills dir. It is
// INSIDE the owned subtree `.cursor/rules/soma`, so the install-time
// reconcileOwnedSubtrees prunes stale skills and `uninstall.remove` already
// covers them — no separate install manifest (unlike claude-code/grok, whose
// skills dir is shared). The VSA skill (`.../skills/VSA`) is projected by its
// own installer and excluded from reconcile.
export const CURSOR_SKILLS_DIR_PREFIX = ".cursor/rules/soma/skills/";

export const CURSOR_HOME_FILE_PATHS = [
  CURSOR_RULES_PATH,
  CURSOR_RULES_README_PATH,
  CURSOR_CONTEXT_PATH,
  CURSOR_PROFILE_PATH,
  CURSOR_PURPOSE_PATH,
  CURSOR_MEMORY_LAYOUT_PATH,
  CURSOR_SKILLS_PATH,
  CURSOR_POLICY_PATH,
  CURSOR_MCP_PATH,
] as const;

export function isCursorSkillProjectionPath(path: string): boolean {
  return path.startsWith(CURSOR_SKILLS_DIR_PREFIX);
}

export function cursorWorkspaceSubstrateHome(cwd: string = process.cwd()): string {
  return resolve(cwd);
}

function renderInstructions(input: ProjectionInput): string {
  return [
    "# Soma Cursor Context",
    "",
    "You are running inside Cursor with Soma-projected assistant context.",
    "Treat Soma as the source of truth. Treat Cursor rules and composer context as projections.",
    "",
    renderAssistantCore(input),
    "",
    "## Operating Rules",
    "- Read the Soma rule files under `.cursor/rules/soma/` before acting as the Soma assistant.",
    "- Use the active VSA as the verification contract when present.",
    "- Keep Cursor-specific behavior behind the Cursor adapter boundary.",
    "- Record verification and any Cursor-specific limitation in the task result.",
  ].join("\n");
}

function renderCursorRules(): string {
  return [
    "# Soma Cursor Projection",
    "",
    "This file is generated by Soma. The portable source of truth is the Soma home.",
    "",
    "Use `.cursor/rules/soma/CONTEXT.md` as the primary assistant context.",
    "Use `.cursor/rules/soma/MEMORY_LAYOUT.md`, `SKILLS.md`, `POLICY.md`, and `ACTIVE_VSA.md` when those files are present.",
    "",
    "Do not edit this file by hand; rerun `soma install cursor --apply` after changing Soma source context.",
  ].join("\n");
}

function renderCursorRulesReadme(): string {
  return [
    "# Soma Cursor Projection",
    "",
    "This directory is generated by Soma for Cursor.",
    "",
    "Cursor reads `.cursorrules` and project rules as context. Soma keeps the portable source of truth outside Cursor and projects a compact rule set here.",
    "",
    "## Files",
    "",
    "- `CONTEXT.md` — assistant identity, principal, purpose, and operating rules",
    "- `PROFILE.md` — assistant and principal profile detail",
    "- `PURPOSE.md` — mission, goals, principles, and commitments",
    "- `MEMORY_LAYOUT.md` — pointers into the Soma memory tree",
    "- `SKILLS.md` — discovered Soma skills",
    "- `POLICY.md` — substrate policy projection",
    "- `MCP.md` — MCP integration notes for future on-demand skill loading",
    "- `ACTIVE_VSA.md` — current active VSA, omitted when none is active",
    "",
    "Manual edits are overwritten on the next install. Author changes in Soma and re-project.",
  ].join("\n");
}

function renderCursorProfile(input: ProjectionInput): string {
  return ["# Soma Profile Projection", "", renderAssistantCore(input)].join("\n");
}

function renderCursorPurpose(input: ProjectionInput): string {
  const t = input.profile.purpose;
  return [
    "# Soma Purpose Projection",
    "",
    t.mission ? `## Mission\n\n${t.mission}` : "## Mission\n\nNone declared.",
    "",
    "## Goals",
    "",
    t.goals.length === 0 ? "- None declared" : t.goals.map((g) => `- ${g}`).join("\n"),
    "",
    "## Principles",
    "",
    t.principles.length === 0 ? "- None declared" : t.principles.map((p) => `- ${p}`).join("\n"),
    "",
    "## Commitments",
    "",
    t.commitments.length === 0 ? "- None declared" : t.commitments.map((c) => `- ${c}`).join("\n"),
  ].join("\n");
}

function renderCursorMcpNotes(): string {
  return [
    "# Cursor MCP Integration",
    "",
    "Cursor can use MCP servers for on-demand tools and skill loading, but Soma does not ship a Cursor-specific MCP server yet.",
    "",
    "Current projection contract:",
    "",
    "- Eager kernel context is projected through `.cursorrules` and `.cursor/rules/soma/`.",
    "- Skills are listed in `SKILLS.md` for routing and manual inspection.",
    "- Future MCP wiring should expose read-only skill lookup and memory search without making Cursor the source of truth.",
  ].join("\n");
}

function renderCursorPolicy(): string {
  return renderPolicyProjection(
    "cursor",
    ["Cursor rules and composer context"],
    [
      "MCP permission prompts when configured",
      "Verification reporting",
      "Private context handling",
    ],
  );
}

export function projectCursor(input: ProjectionInput): Projection {
  const instructions = renderInstructions(input);
  // Portable bundled skills (the-algorithm, Memory) project as invocable dirs
  // under the Soma-owned Cursor skills dir. VSA excluded (dedicated installer).
  // Same default substrate rewrite as codex/grok/claude-code.
  const portableSkillFiles = buildPortableSkillFiles(input.profile.skills, input.bundledSkillNames, "cursor", {
    skillsDirPrefix: CURSOR_SKILLS_DIR_PREFIX,
  });

  return {
    substrate: "cursor",
    instructions,
    files: [
      ...portableSkillFiles,
      {
        // Excluded from withProvenance: this file's content becomes the BODY
        // of a hand-maintained-file merge block (home-projection.ts wraps it
        // in CURSOR_RULES_BLOCK_BEGIN/END and splices it into a possibly
        // foreign-owned .cursorrules), so its own "managed" signal is the
        // block markers, not the HTML-comment provenance header (soma#370
        // investigation).
        path: CURSOR_RULES_PATH,
        content: renderCursorRules(),
      },
      {
        // soma#370: plain markdown narrative files under the owned
        // `.cursor/rules/soma/` subtree carry the byte-stable provenance
        // header so `soma doctor` can distinguish a managed projection from
        // a hand-replaced one.
        path: CURSOR_RULES_README_PATH,
        content: withProvenance("cursor", renderCursorRulesReadme()),
      },
      {
        path: CURSOR_CONTEXT_PATH,
        content: withProvenance("cursor", instructions),
      },
      {
        path: CURSOR_PROFILE_PATH,
        content: withProvenance("cursor", renderCursorProfile(input)),
      },
      {
        path: CURSOR_PURPOSE_PATH,
        content: withProvenance("cursor", renderCursorPurpose(input)),
      },
      {
        path: CURSOR_MEMORY_LAYOUT_PATH,
        content: withProvenance("cursor", renderMemoryLayout(input)),
      },
      {
        path: CURSOR_SKILLS_PATH,
        content: withProvenance("cursor", renderSkills(input)),
      },
      {
        path: CURSOR_POLICY_PATH,
        content: withProvenance("cursor", renderCursorPolicy()),
      },
      {
        path: CURSOR_MCP_PATH,
        content: withProvenance("cursor", renderCursorMcpNotes()),
      },
      ...activeVsaBundleFile("cursor", input.activeVsa),
    ],
  };
}

export function projectCursorHome(input: ProjectionInput): Projection {
  return projectCursor(input);
}

export const cursorAdapter: SomaAdapter = {
  name: "cursor",
  detect() {
    return Promise.resolve(Boolean(process.env.CURSOR_TRACE_ID ?? process.env.CURSOR_APP_PATH));
  },
  project(input) {
    return Promise.resolve(projectCursor(input));
  },
  run(task: SomaTask) {
    return Promise.resolve({
      taskId: task.id,
      substrate: "cursor",
      status: "failed",
      summary: "Cursor execution is not implemented yet; use project() to generate the context projection.",
    });
  },
};
