/**
 * Render a pi.dev extension that guards against destructive operations on
 * protected paths (Soma home, PAI home, Pi home, etc.).
 *
 * The extension intercepts tool_call events for bash commands and blocks
 * destructive operations targeting protected directories. It also guards
 * write/edit tools targeting paths inside protected directories.
 *
 * SUBSTRATE-SPECIFIC: This renders pi.dev extension code. Other substrates
 * (Claude Code, Codex) get their own enforcement generators.
 */
export function renderPathGuardExtension(somaHome: string): string {
  const dq = "\u0022"; // double-quote character for string building

  return [
    `import type { ExtensionAPI } from ${dq}@mariozechner/pi-coding-agent${dq};`,
    "",
    `const SOMA_HOME = ${JSON.stringify(somaHome)};`,
    "",
    "// Protected paths inherited from Soma path guard policy.",
    "const PROTECTED_PATHS = [",
    `  { path: ${JSON.stringify("~/.soma")}, description: ${JSON.stringify("Soma portable assistant home")} },`,
    `  { path: ${JSON.stringify("~/.claude")}, description: ${JSON.stringify("Claude Code / PAI home")} },`,
    `  { path: ${JSON.stringify("~/.pi")}, description: ${JSON.stringify("Pi.dev home")} },`,
    `  { path: ${JSON.stringify("~/.config/cortex")}, description: ${JSON.stringify("Cortex operator config")} },`,
    `  { path: ${JSON.stringify("~/.config/metafactory")}, description: ${JSON.stringify("Metafactory ecosystem config")} },`,
    `  { path: ${JSON.stringify("~/.config/k")}, description: ${JSON.stringify("kai-launcher config")} },`,
    "];",
    "",
    "const DESTRUCTIVE_DELETE = new Set([",
    "  " + ["rm", "rmdir", "trash", "trash-put", "gtrash"].map((c) => JSON.stringify(c)).join(", "),
    "]);",
    "",
    "const DESTRUCTIVE_MOVE = new Set([",
    "  " + ["mv"].map((c) => JSON.stringify(c)).join(", "),
    "]);",
    "",
    "function expandTilde(path: string): string {",
    "  if (path === " + JSON.stringify("~") + ") return process.env.HOME || " + JSON.stringify("/") + ";",
    "  if (path.startsWith(" + JSON.stringify("~/") + ")) return process.env.HOME + path.slice(1);",
    "  return path;",
    "}",
    "",
    "function isInside(path: string, root: string): boolean {",
    "  const rel = require(" + JSON.stringify("node:path") + ").relative(root, path);",
    "  return rel === " + JSON.stringify("") + " || (!rel.startsWith(" + JSON.stringify("..") + ") && !require(" + JSON.stringify("node:path") + ").isAbsolute(rel));",
    "}",
    "",
    "function isProtected(target: string): { blocked: boolean; detail: string } {",
    "  const resolved = require(" + JSON.stringify("node:path") + ").resolve(expandTilde(target));",
    "  for (const pp of PROTECTED_PATHS) {",
    "    const root = require(" + JSON.stringify("node:path") + ").resolve(expandTilde(pp.path));",
    "    if (isInside(resolved, root)) {",
    "      return { blocked: true, detail: target + " + JSON.stringify(" is under ") + " + pp.path + " + JSON.stringify(" (") + " + pp.description + " + JSON.stringify(")") + " };",
    "    }",
    "  }",
    "  return { blocked: false, detail: " + JSON.stringify("") + " };",
    "}",
    "",
    "function cleanToken(token: string): string {",
    "  let cleaned = token;",
    "  const SQ = " + JSON.stringify("'") + ";",
    "  const DQ = " + JSON.stringify('"') + ";",
    "  if ((cleaned.startsWith(DQ) && cleaned.endsWith(DQ)) || (cleaned.startsWith(SQ) && cleaned.endsWith(SQ))) {",
    "    cleaned = cleaned.slice(1, -1);",
    "  }",
    "  cleaned = cleaned.replace(/^[<>]+/, " + JSON.stringify("") + ").replace(/>$/, " + JSON.stringify("") + ");",
    "  return cleaned;",
    "}",
    "",
    "function tokenize(command: string): string[] {",
    "  const tokens: string[] = [];",
    "  const re = /" + dq + "([^" + dq + "]*)" + dq + "|'([^']*)'|[^\\s]+/g;",
    "  let match: RegExpExecArray | null;",
    "  while ((match = re.exec(command)) !== null) {",
    "    const raw = match[1] ?? match[2] ?? match[0];",
    "    tokens.push(cleanToken(raw));",
    "  }",
    "  return tokens;",
    "}",
    "",
    "function extractDestructiveTargets(command: string, cwd: string): string[] {",
    "  const tokens = tokenize(command);",
    "  if (tokens.length === 0) return [];",
    "",
    "  let cmdIndex = 0;",
    "  const prefixes = new Set([" + ["sudo", "bun", "node", "npx", "bunx", "time", "nice", "exec", "env", "nohup"].map((c) => JSON.stringify(c)).join(", ") + "]);",
    "  while (cmdIndex < tokens.length && prefixes.has(tokens[cmdIndex])) cmdIndex++;",
    "  if (cmdIndex >= tokens.length) return [];",
    "",
    "  const mainCommand = tokens[cmdIndex];",
    "  const isDelete = DESTRUCTIVE_DELETE.has(mainCommand);",
    "  const isMove = DESTRUCTIVE_MOVE.has(mainCommand);",
    "  if (!isDelete && !isMove) return [];",
    "",
    "  const chainOps = new Set([" + [";", "&&", "||", "|"].map((c) => JSON.stringify(c)).join(", ") + "]);",
    "  const targets: string[] = [];",
    "  for (let i = cmdIndex + 1; i < tokens.length; i++) {",
    "    const token = tokens[i];",
    "    if (chainOps.has(token)) break;",
    "    if (token.startsWith(" + JSON.stringify("-") + ")) continue;",
    "    targets.push(token);",
    "  }",
    "",
    "  if (isMove) {",
    "    return targets.length >= 1 ? [targets[0]] : [];",
    "  }",
    "",
    "  const resolved = targets.map(t => require(" + JSON.stringify("node:path") + ").resolve(cwd, expandTilde(t)));",
    "  if (resolved.length === 0 && (command.includes(" + JSON.stringify(" *") + ") || command.endsWith(" + JSON.stringify("*") + ") || command.includes(" + JSON.stringify("* ") + "))) {",
    "    return [cwd];",
    "  }",
    "  return resolved;",
    "}",
    "",
    "export default function (pi: ExtensionAPI) {",
    "  pi.on(" + JSON.stringify("tool_call") + ", async (event, ctx) => {",
    "    // Guard destructive bash commands",
    "    if (event.toolName === " + JSON.stringify("bash") + " || event.toolName === " + JSON.stringify("Bash") + ") {",
    "      const input = (event as { input?: { command?: string; timeout?: number } }).input;",
    "      if (!input?.command) return;",
    "",
    "      const cwd = (ctx as { cwd?: string }).cwd ?? process.cwd();",
    "      const targets = extractDestructiveTargets(input.command, cwd);",
    "",
    "      const blockedTargets: string[] = [];",
    "      const blockDetails: string[] = [];",
    "      for (const target of targets) {",
    "        const result = isProtected(target);",
    "        if (result.blocked) {",
    "          blockedTargets.push(target);",
    "          blockDetails.push(result.detail);",
    "        }",
    "      }",
    "",
    "      if (blockedTargets.length > 0) {",
    "        const detail = blockDetails.join(" + JSON.stringify("; ") + ");",
    "        const msg = " + JSON.stringify("Soma path guard blocked destructive command: ") + " + input.command + " + JSON.stringify(". Protected: ") + " + detail + " + JSON.stringify(".") + ";",
    "        ctx.ui?.notify?.(msg, " + JSON.stringify("error") + ");",
    "        return { block: true, reason: msg };",
    "      }",
    "    }",
    "",
    "    // Guard write/edit tools targeting protected paths",
    "    if (event.toolName === " + JSON.stringify("write") + " || event.toolName === " + JSON.stringify("Write") + " ||",
    "        event.toolName === " + JSON.stringify("edit") + " || event.toolName === " + JSON.stringify("Edit") + ") {",
    "      const input = (event as { input?: { file_path?: string; path?: string } }).input;",
    "      const targetPath = input?.file_path ?? input?.path;",
    "      if (!targetPath) return;",
    "",
    "      const result = isProtected(targetPath);",
    "      if (result.blocked) {",
    "        const msg = " + JSON.stringify("Soma path guard blocked write to protected path: ") + " + result.detail + " + JSON.stringify(".") + ";",
    "        ctx.ui?.notify?.(msg, " + JSON.stringify("error") + ");",
    "        return { block: true, reason: msg };",
    "      }",
    "    }",
    "  });",
    "}",
  ].join("\n");
}
