import type { SomaAdapter, SomaContextBundle, SomaContextInput, SomaTask } from "../types";
import { renderAssistantCore, renderMemoryLayout, renderPolicyProjection, renderSkills } from "./shared";

function renderInstructions(input: SomaContextInput): string {
  return [
    "# Soma Pi.dev Context",
    "",
    "You are running inside Pi.dev with Soma-projected assistant context.",
    "Treat Soma as the portable assistant kernel. Treat Pi.dev extensions and tools as the host execution surface.",
    "",
    renderAssistantCore(input),
    "",
    "## Operating Rules",
    "- Use Soma tools for ISA, memory, learning, and policy operations when available.",
    "- Keep model-provider settings outside the Soma core.",
    "- Prefer file-backed memory paths from the bundle over substrate-local hidden state.",
    "- Report extension/tool limitations as adapter limitations.",
  ].join("\n");
}

function renderExtensionManifest(): string {
  return `${JSON.stringify(
    {
      name: "soma-core",
      version: "0.1.1",
      description: "Pi.dev projection for Soma personal assistant context.",
      tools: [
        "isa_create",
        "isa_update",
        "memory_search",
        "soma_memory_promote",
        "capture_learning",
        "policy_check",
      ],
    },
    null,
    2,
  )}\n`;
}

function renderToolContract(): string {
  return [
    "# Soma Pi.dev Tool Contract",
    "",
    "The first Pi.dev adapter projects the tool surface only. Implementations stay outside the portable core until Pi.dev execution is wired.",
    "",
    "- `isa_create`: create a personal/task ISA in Soma memory.",
    "- `isa_update`: update an existing ISA criterion, phase, or verification record.",
    "- `memory_search`: search the declared file-backed memory layout.",
    "- `soma_memory_promote`: promote verified Algorithm work into durable Soma memory.",
    "- `capture_learning`: append a learning note through an explicit write path.",
    "- `policy_check`: report enforceable and advisory policy status for a requested action.",
  ].join("\n");
}

function renderPaiImportIndex(somaHome: string): string {
  const importRoot = `${somaHome}/profile/imports/claude`;

  return [
    "# Soma PAI Import Index",
    "",
    "The projected profile is intentionally concise. Detailed migrated PAI source snapshots remain in Soma and should be read when the task depends on personal identity, assistant voice, telos, values, goals, strategies, or decision context.",
    "",
    "## Source Root",
    "",
    importRoot,
    "",
    "## Read For Detail",
    "",
    `- Principal identity: ${importRoot}/PRINCIPAL_IDENTITY.md`,
    `- Ivy assistant identity and voice: ${importRoot}/DA_IDENTITY.md`,
    `- Mission: ${importRoot}/TELOS/MISSION.md`,
    `- Goals: ${importRoot}/TELOS/GOALS.md`,
    `- Strategies: ${importRoot}/TELOS/STRATEGIES.md`,
    `- Beliefs and values: ${importRoot}/TELOS/BELIEFS.md`,
    "",
    "## Use Rule",
    "",
    "Use `profile.md` for fast orientation. Read the imported source files before making durable claims about Jens-Christian, Ivy, values, goals, priorities, or preferred collaboration style.",
  ].join("\n");
}

function renderHomeExtension(somaHome: string): string {
  return [
    'import { execFile, spawnSync } from "node:child_process";',
    'import { readFileSync, writeFileSync } from "node:fs";',
    'import { promisify } from "node:util";',
    'import { StringEnum } from "@mariozechner/pi-ai";',
    'import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";',
    'import { Type } from "@sinclair/typebox";',
    "",
    `const SOMA_HOME = ${JSON.stringify(somaHome)};`,
    'const PI_SOMA_HOME = `${process.env.HOME}/.pi/agent/soma`;',
    'const PI_SKILLS_HOME = `${process.env.HOME}/.pi/agent/skills`;',
    "const execFileAsync = promisify(execFile);",
    "",
    "const SomaContextParams = Type.Object({",
    '\taction: StringEnum(["profile", "startup_context", "algorithm_work_index", "memory_layout", "pai_imports", "source_file", "memory_search"] as const),',
    '\tpath: Type.Optional(Type.String({ description: "Absolute Soma source file path for action=source_file" })),',
    '\tquery: Type.Optional(Type.String({ description: "Search query for action=memory_search" })),',
    "\tlimit: Type.Optional(Type.Number({ description: \"Maximum memory_search matches\" })),",
    "});",
    "",
    "const SomaMemoryPromoteParams = Type.Object({",
    '\tfromRun: Type.Optional(Type.String({ description: "Algorithm run id for action=memory_promote" })),',
    '\tstore: Type.Optional(StringEnum(["learning", "knowledge", "relationship", "work"] as const)),',
    '\ttitle: Type.Optional(Type.String({ description: "Memory title for action=memory_promote" })),',
    '\tlesson: Type.Optional(Type.String({ description: "Durable lesson override for action=memory_promote" })),',
    '\tappliesWhen: Type.Optional(Type.String({ description: "Recall guidance for action=memory_promote" })),',
    "});",
    "",
    "function readText(path: string): string {",
    '\treturn readFileSync(path, "utf8");',
    "}",
    "",
    "function readOptional(path: string): string {",
    "\ttry {",
    "\t\treturn readText(path);",
    "\t} catch {",
    '\t\treturn "";',
    "\t}",
    "}",
    "",
    "function writeText(path: string, content: string): void {",
    '\twriteFileSync(path, `${content.trimEnd()}\\n`, "utf8");',
    "}",
    "",
    "function somaRepoPath(): string {",
    "\tif (process.env.SOMA_REPO) return process.env.SOMA_REPO;",
    "\ttry {",
    '\t\treturn readText(`${PI_SOMA_HOME}/soma-repo.txt`).trim();',
    "\t} catch {",
    "\t\treturn process.cwd();",
    "\t}",
    "}",
    "",
    "function runSomaLifecycle(event: \"session-start\" | \"algorithm-updated\" | \"session-end\", sessionId?: string): { ok: boolean; output: string } {",
    '\tconst args = ["run", "soma", "lifecycle", event, "--soma-home", SOMA_HOME, "--substrate", "pi-dev"];',
    "\tif (sessionId) args.push(\"--session-id\", sessionId);",
    '\tconst result = spawnSync("bun", args, { cwd: somaRepoPath(), encoding: "utf8", timeout: 25000 });',
    '\treturn { ok: result.status === 0, output: result.stdout || result.stderr || "" };',
    "}",
    "",
    "function runSomaClassification(prompt: string): { ok: boolean; output: string } {",
    '\tconst result = spawnSync("bun", ["run", "soma", "algorithm", "classify", "--prompt", prompt], {',
    "\t\tcwd: somaRepoPath(),",
    '\t\tencoding: "utf8",',
    "\t\ttimeout: 25000",
    "\t});",
    '\treturn { ok: result.status === 0, output: result.stdout || result.stderr || "" };',
    "}",
    "",
    "async function runSomaCommand(args: string[]): Promise<string> {",
    "\ttry {",
    '\t\tconst result = await execFileAsync("bun", args, { cwd: somaRepoPath(), encoding: "utf8", timeout: 25000 });',
    "\t\treturn result.stdout || result.stderr || \"\";",
    "\t} catch (error) {",
    "\t\tconst failure = error as { stdout?: string; stderr?: string; message?: string };",
    "\t\treturn failure.stdout || failure.stderr || failure.message || String(error);",
    "\t}",
    "}",
    "",
    "function memorySearchArgs(query: string, limit?: number): string[] {",
    '\tconst args = ["run", "soma", "memory", "search", "--soma-home", SOMA_HOME, "--query", query];',
    "\tif (limit) args.push(\"--limit\", String(limit));",
    "\treturn args;",
    "}",
    "",
    "function memoryPromoteArgs(params: { fromRun?: string; store?: string; title?: string; lesson?: string; appliesWhen?: string }): string[] | string {",
    '\tif (!params.fromRun || !params.store || !params.title) return "Error: fromRun, store, and title are required for memory_promote";',
    '\tconst args = ["run", "soma", "memory", "promote", "--soma-home", SOMA_HOME, "--substrate", "pi-dev", "--from-run", params.fromRun, "--store", params.store, "--title", params.title];',
    "\tif (params.lesson) args.push(\"--lesson\", params.lesson);",
    "\tif (params.appliesWhen) args.push(\"--applies-when\", params.appliesWhen);",
    "\treturn args;",
    "}",
    "",
    "function parseClassification(output: string): Record<string, string> {",
    "\tconst fields: Record<string, string> = {};",
    '\tfor (const line of output.split("\\n")) {',
    '\t\tconst separator = line.indexOf(": ");',
    "\t\tif (separator === -1) continue;",
    "\t\tfields[line.slice(0, separator)] = line.slice(separator + 2).trim();",
    "\t}",
    "\treturn fields;",
    "}",
    "",
    "function promptFromEvent(event: unknown): string {",
    "\tconst value = event as { prompt?: unknown; userPrompt?: unknown; message?: unknown; input?: unknown };",
    '\tfor (const candidate of [value.prompt, value.userPrompt, value.message, value.input]) {',
    '\t\tif (typeof candidate === "string" && candidate.trim().length > 0) return candidate;',
    "\t}",
    '\treturn "";',
    "}",
    "",
    "function renderPromptClassificationContext(prompt: string): string {",
    "\tif (!prompt) return \"Soma: prompt unavailable. Use the-algorithm manually for substantial work.\";",
    "\tconst result = runSomaClassification(prompt);",
    "\tif (!result.ok) return `Soma: classification failed. Use the-algorithm manually for substantial work. ${result.output}`;",
    "\tconst classification = parseClassification(result.output);",
    '\tconst mode = (classification.mode || "algorithm").toUpperCase();',
    '\tconst effort = classification.effort && classification.effort !== "none" ? classification.effort : "";',
    '\tconst source = classification.source || "unknown";',
    "\tconst label = effort ? `${mode} ${effort}` : mode;",
    "",
    '\tif (mode === "ALGORITHM") {',
    "\t\treturn `Soma: ${label} (${source}). Use the-algorithm; create/update the run and record verification evidence.`;",
    "\t}",
    "",
    "\treturn `Soma: ${label} (${source}). Full Algorithm harness optional unless context makes it substantial.`;",
    "}",
    "",
    "function extractStartupContext(output: string): string | undefined {",
    '\tconst marker = "# Soma Startup Context";',
    "\tconst index = output.indexOf(marker);",
    "\treturn index === -1 ? undefined : output.slice(index).trim();",
    "}",
    "",
    "function refreshStartupContext(sessionId?: string): string {",
    '\tconst result = runSomaLifecycle("session-start", sessionId);',
    "\tconst fresh = result.ok ? extractStartupContext(result.output) : undefined;",
    "\tif (fresh) {",
    '\t\twriteText(`${PI_SOMA_HOME}/startup-context.md`, fresh);',
    "\t\treturn fresh;",
    "\t}",
    '\treturn readOptional(`${PI_SOMA_HOME}/startup-context.md`);',
    "}",
    "",
    "function refreshWorkIndex(): void {",
    '\trunSomaLifecycle("algorithm-updated");',
    "}",
    "",
    "function captureSessionEnd(sessionId?: string): void {",
    '\trunSomaLifecycle("session-end", sessionId);',
    "}",
    "",
    "function targetForAction(action: string, path?: string): string | undefined {",
    '\tif (action === "profile") return `${PI_SOMA_HOME}/profile.md`;',
    '\tif (action === "startup_context") return `${PI_SOMA_HOME}/startup-context.md`;',
    '\tif (action === "algorithm_work_index") return `${SOMA_HOME}/memory/STATE/algorithm-work-index.json`;',
    '\tif (action === "memory_layout") return `${PI_SOMA_HOME}/memory-layout.md`;',
    '\tif (action === "pai_imports") return `${PI_SOMA_HOME}/pai-imports.md`;',
    "\treturn path;",
    "}",
    "",
    "function sessionId(ctx: { sessionManager?: { getSessionFile?: () => string | undefined } }): string | undefined {",
    "\treturn ctx.sessionManager?.getSessionFile?.();",
    "}",
    "",
    "export default function (pi: ExtensionAPI) {",
    '\tpi.on("resources_discover", async () => {',
    "\t\treturn { skillPaths: [PI_SKILLS_HOME] };",
    "\t});",
    "",
    '\tpi.on("session_start", async (_event, ctx) => {',
    "\t\trefreshStartupContext(sessionId(ctx));",
    "\t\trefreshWorkIndex();",
    '\t\tctx.ui?.setStatus?.("soma", "Soma ready");',
    "\t});",
    "",
    '\tpi.on("before_agent_start", async (event, ctx) => {',
    '\t\tconst profile = readOptional(`${PI_SOMA_HOME}/profile.md`);',
    "\t\tconst startupContext = refreshStartupContext(sessionId(ctx));",
    '\t\tconst paiImports = readOptional(`${PI_SOMA_HOME}/pai-imports.md`);',
    '\t\tconst context = readOptional(`${PI_SOMA_HOME}/context.md`);',
    "\t\tconst promptClassification = renderPromptClassificationContext(promptFromEvent(event));",
    '\t\tconst somaPrompt = `',
    "## Soma Personal Assistant Context",
    "",
    "Soma is the portable personal assistant source of truth for this Pi.dev session.",
    "When the user asks who you are, answer as the Soma-projected assistant identity, while acknowledging Pi.dev as the execution substrate when useful.",
    "When the user asks who they are, answer from the Soma-projected principal identity.",
    "Use the soma_context tool or read paths listed below when deeper migrated PAI identity, values, goals, strategies, or decision context matters.",
    "",
    "${profile}",
    "",
    "${startupContext}",
    "",
    "${paiImports}",
    "",
    "${context}",
    "",
    "${promptClassification}",
    "`;",
    "",
    "\t\treturn {",
    "\t\t\tsystemPrompt: `${event.systemPrompt}\\n\\n${somaPrompt}`,",
    "\t\t};",
    "\t});",
    "",
    '\tpi.on("agent_start", async (_event, ctx) => {',
    '\t\tctx.ui?.setStatus?.("soma", "Algorithm active");',
    "\t});",
    "",
    '\tpi.on("tool_execution_end", async (event) => {',
    "\t\tconst name = String(event.toolName ?? \"\").toLowerCase();",
    '\t\tif (/(edit|write|patch|bash|shell)/.test(name)) refreshWorkIndex();',
    "\t});",
    "",
    '\tpi.on("agent_end", async () => {',
    "\t\trefreshWorkIndex();",
    "\t});",
    "",
    '\tpi.on("session_before_compact", async () => {',
    "\t\trefreshWorkIndex();",
    "\t});",
    "",
    '\tpi.on("session_shutdown", async (_event, ctx) => {',
    "\t\tcaptureSessionEnd(sessionId(ctx));",
    "\t});",
    "",
    "\tpi.registerTool({",
    '\t\tname: "soma_context",',
    '\t\tlabel: "Soma Context",',
    '\t\tdescription: "Read projected Soma personal assistant context and migrated PAI source snapshots.",',
    "\t\tparameters: SomaContextParams,",
    "",
    "\t\tasync execute(_toolCallId, params) {",
    "\t\t\tif (params.action === \"startup_context\") refreshStartupContext();",
    "\t\t\tif (params.action === \"algorithm_work_index\") refreshWorkIndex();",
    "\t\t\tif (params.action === \"memory_search\") {",
    "\t\t\t\tif (!params.query) return { content: [{ type: \"text\", text: \"Error: query is required for memory_search\" }] };",
    "\t\t\t\treturn { content: [{ type: \"text\", text: await runSomaCommand(memorySearchArgs(params.query, params.limit)) }] };",
    "\t\t\t}",
    "\t\t\tconst target = targetForAction(params.action, params.path);",
    "",
    "\t\t\tif (!target) {",
    '\t\t\t\treturn { content: [{ type: "text", text: "Error: path is required for source_file" }] };',
    "\t\t\t}",
    "",
    "\t\t\tif (params.action === \"source_file\" && !target.startsWith(SOMA_HOME)) {",
    '\t\t\t\treturn { content: [{ type: "text", text: `Error: refusing to read outside Soma home: ${target}` }] };',
    "\t\t\t}",
    "",
    "\t\t\ttry {",
    '\t\t\t\treturn { content: [{ type: "text", text: readText(target) }] };',
    "\t\t\t} catch (error) {",
    '\t\t\t\treturn { content: [{ type: "text", text: `Error reading ${target}: ${error instanceof Error ? error.message : String(error)}` }] };',
    "\t\t\t}",
    "\t\t},",
    "\t});",
    "",
    "\tpi.registerTool({",
    '\t\tname: "soma_memory_promote",',
    '\t\tlabel: "Soma Memory Promote",',
    '\t\tdescription: "Promote verified Algorithm work into durable Soma memory.",',
    "\t\tparameters: SomaMemoryPromoteParams,",
    "",
    "\t\tasync execute(_toolCallId, params) {",
    "\t\t\tconst args = memoryPromoteArgs(params);",
    "\t\t\treturn { content: [{ type: \"text\", text: typeof args === \"string\" ? args : await runSomaCommand(args) }] };",
    "\t\t},",
    "\t});",
    "",
    '\tpi.registerCommand("soma", {',
    '\t\tdescription: "Show Soma profile, lifecycle context, and PAI import pointers",',
    "\t\thandler: async (_args, ctx) => {",
    "\t\t\tconst startupContext = refreshStartupContext(sessionId(ctx));",
    '\t\t\tconst text = [readText(`${PI_SOMA_HOME}/profile.md`), "", startupContext, "", readText(`${PI_SOMA_HOME}/pai-imports.md`)].join("\\n");',
    "\t\t\tctx.ui.notify(text, \"info\");",
    "\t\t},",
    "\t});",
    "}",
  ].join("\n");
}

function renderHomeSkill(input: SomaContextInput, somaHome: string): string {
  return [
    "---",
    "name: soma",
    "description: Use when work depends on Soma portable personal assistant context, Ivy assistant identity, Jens-Christian principal identity, telos, PAI imports, memory layout, or cross-substrate continuity.",
    "metadata:",
    "  short-description: Portable personal assistant context",
    "---",
    "",
    "# Soma",
    "",
    `Source of truth: ${somaHome}`,
    "",
    "## Use",
    "",
    "- Use the `soma_context` tool with `action: profile` for fast orientation.",
    "- Use the `soma_context` tool with `action: startup_context` for lifecycle-generated active work and recent learning context.",
    "- Use the `soma_context` tool with `action: algorithm_work_index` for canonical Algorithm work state.",
    "- Use the `soma_context` tool with `action: memory_search` before making durable claims that may depend on prior knowledge, learning, relationship, work, or imported PAI context.",
    "- Use the `soma_memory_promote` tool when verified Algorithm work should become durable recall.",
    "- Use the `soma_context` tool with `action: pai_imports` to find detailed migrated PAI source files.",
    "- Use the `soma_context` tool with `action: source_file` for detailed identity, voice, telos, values, goals, strategies, and decision-context source files under Soma.",
    "- Do not assume a global `soma` binary exists; the SomaExtension calls the repo CLI via `~/.pi/agent/soma/soma-repo.txt`.",
    "- Treat Pi.dev as the execution substrate, not the source of truth.",
    "",
    "## Current Projection",
    "",
    renderAssistantCore(input),
  ].join("\n");
}

export function buildPiDevContext(input: SomaContextInput): SomaContextBundle {
  const instructions = renderInstructions(input);

  return {
    substrate: "pi-dev",
    instructions,
    files: [
      {
        path: ".pi/extensions/soma-core/extension.json",
        content: renderExtensionManifest(),
      },
      {
        path: ".pi/extensions/soma-core/context.md",
        content: instructions,
      },
      {
        path: ".pi/extensions/soma-core/tools.md",
        content: renderToolContract(),
      },
      {
        path: ".pi/extensions/soma-core/memory-layout.md",
        content: renderMemoryLayout(input),
      },
      {
        path: ".pi/extensions/soma-core/skills.md",
        content: renderSkills(input),
      },
      {
        path: ".pi/extensions/soma-core/policy.md",
        content: renderPolicyProjection("pi-dev", ["Registered extension tools once installed"], [
          "Model-provider behavior",
          "Host permission prompts",
          "Verification reporting",
        ]),
      },
    ],
  };
}

export function buildPiDevHomeContext(input: SomaContextInput, somaHome: string): SomaContextBundle {
  const instructions = renderInstructions(input);
  const portableSkillFiles = input.profile.skills.flatMap((skill) =>
    (skill.files ?? []).map((file) => ({
      path: `agent/skills/${skill.name}/${file.path}`,
      content: file.content,
    })),
  );

  return {
    substrate: "pi-dev",
    instructions,
    files: [
      {
        path: "agent/extensions/soma.ts",
        content: renderHomeExtension(somaHome),
      },
      {
        path: "agent/soma/context.md",
        content: instructions,
      },
      {
        path: "agent/soma/profile.md",
        content: ["# Soma Profile Projection", "", renderAssistantCore(input)].join("\n"),
      },
      {
        path: "agent/soma/memory-layout.md",
        content: renderMemoryLayout(input),
      },
      {
        path: "agent/soma/pai-imports.md",
        content: renderPaiImportIndex(somaHome),
      },
      {
        path: "agent/soma/tools.md",
        content: renderToolContract(),
      },
      {
        path: "agent/soma/skills.md",
        content: renderSkills(input),
      },
      {
        path: "agent/soma/policy.md",
        content: renderPolicyProjection("pi-dev", ["soma_context extension tool reads projected context and Soma source snapshots"], [
          "Model-provider behavior",
          "Host permission prompts",
          "Verification reporting",
        ]),
      },
      {
        path: "agent/skills/soma/SKILL.md",
        content: renderHomeSkill(input, somaHome),
      },
      ...portableSkillFiles,
    ],
  };
}

export const piDevAdapter: SomaAdapter = {
  name: "pi-dev",
  detect() {
    return Promise.resolve(Boolean(process.env.PI_DEV_HOME ?? process.env.PIDEV_HOME));
  },
  buildContext(input) {
    return Promise.resolve(buildPiDevContext(input));
  },
  run(task: SomaTask) {
    return Promise.resolve({
      taskId: task.id,
      substrate: "pi-dev",
      status: "failed",
      summary: "Pi.dev execution is not implemented yet; use buildContext() to generate the extension bundle.",
    });
  },
};
