/**
 * Render the soma-algorithm pi.dev extension source as a TypeScript
 * string. Soma-issue-43 minimal-correct slice (AC-1, AC-4, AC-5, AC-6
 * code paths; AC-2 wiring lives in adapter.ts + install.ts).
 *
 * Mirrors the `renderPathGuardExtension` pattern (`path-guard.ts`):
 *
 *   - Returned string is written verbatim to `~/.pi/agent/extensions/
 *     soma-algorithm.ts` by the pi-dev home projection.
 *   - Pi.dev hot-reloads `.ts`, so no build step at install time.
 *   - Pure-logic helpers (`phase-parser`, `widget-renderers`,
 *     `isa-checklist`) are imported via a `file://` URL into the
 *     compiled Soma repo so the runtime stays in lockstep with the
 *     parser unit tests — no string-bundled duplicate logic to drift.
 *
 * Open-question resolutions baked into this file (see issue body):
 *   Q1 (TS vs JS):       ship `.ts`.
 *   Q2 (concurrent runs): widget keys include `runId`.
 *   Q3 (version probe):   install-time probe in `installSomaForPiDev`.
 *   Q4 (other substrates): pi.dev only.
 *
 * Pi.dev `ExtensionAPI` is NOT a Soma build-time dep. The extension
 * imports the type from `@mariozechner/pi-coding-agent` directly — that
 * package resolves at pi.dev runtime where the extension actually
 * executes. Soma's package.json is unchanged.
 */

import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export interface RenderSomaAlgorithmExtensionOptions {
  /**
   * Override the runtime module specifier used by the extension to
   * import the pure-logic helpers. Defaults to the absolute `file://`
   * URL of the Soma repo's `phase-parser.ts`/`widget-renderers.ts`/
   * `isa-checklist.ts`. Override is only useful in unit tests.
   */
  readonly runtimeModuleDir?: string;
  readonly somaHome?: string;
}

function defaultRuntimeModuleDir(): string {
  return pathToFileURL(join(import.meta.dir, "/")).href;
}

/**
 * Render the soma-algorithm extension TypeScript source.
 *
 * The returned string is exactly what gets written to disk at
 * `~/.pi/agent/extensions/soma-algorithm.ts`.
 */
export function renderSomaAlgorithmExtension(options: RenderSomaAlgorithmExtensionOptions = {}): string {
  const runtimeDir = options.runtimeModuleDir ?? defaultRuntimeModuleDir();
  const sourceDir = defaultRuntimeModuleDir();
  // Trailing slash is preserved by pathToFileURL when the input is a dir.
  // Helper module specifiers — each helper lives in its own file in
  // src/adapters/pi-dev/extensions/.
  const parserModule = JSON.stringify(`${runtimeDir}phase-parser.ts`);
  const widgetsModule = JSON.stringify(`${runtimeDir}widget-renderers.ts`);
  const checklistModule = JSON.stringify(`${runtimeDir}isa-checklist.ts`);
  const policyModule = JSON.stringify(options.runtimeModuleDir ? `${runtimeDir}policy-audit.ts` : new URL("../../../policy-audit.ts", sourceDir).href);
  const policyTargetsModule = JSON.stringify(options.runtimeModuleDir ? `${runtimeDir}policy-targets.ts` : new URL("policy-targets.ts", sourceDir).href);
  const runSnapshotModule = JSON.stringify(options.runtimeModuleDir ? `${runtimeDir}algorithm-run-snapshot.ts` : new URL("../algorithm-run-snapshot.ts", sourceDir).href);
  const installedSomaHome = JSON.stringify(options.somaHome ?? `${process.env.HOME ?? ""}/.soma`);
  const somaCliEntrypoint = JSON.stringify(fileURLToPath(new URL("../../../cli.ts", sourceDir)));

  return `// soma-algorithm pi.dev extension — generated by Soma. Do not edit by hand.
//
// Renders an active Soma Algorithm run as persistent, per-phase widgets:
//
//   ▸ soma-<runId>-phase-1-observe   ...   soma-<runId>-phase-7-summary
//   ▸ soma-<runId>-isa-criteria
//   ▸ status slot "soma" = "Phase N/7 — NAME"
//
// Requires the pi.dev ExtensionAPI surface pinned by Soma's install-time
// version probe: widgets/status, message_update, session entries, and
// tool_call blocking. If a primitive is unexpectedly absent, optional
// call sites no-op except policy checks, which fail closed.

import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { execFile } from "node:child_process";
import { checkSomaPolicy } from ${policyModule};
import {
  extractToolCallPolicyTargets,
  somaPolicyActionForToolAction,
} from ${policyTargetsModule};
import {
  hydrateAlgorithmRunSnapshot,
  isAlgorithmRunSnapshotComplete,
  snapshotAlgorithmRunState,
  type AlgorithmRunSnapshot,
} from ${runSnapshotModule};
import {
  ALGORITHM_PHASES,
  parseAlgorithmPhaseMarkers,
  type AlgorithmPhaseKey,
  type PhaseMarker,
} from ${parserModule};
import {
  isaCriteriaWidgetKey,
  phaseWidgetKey,
  renderPhaseOverviewLines,
  renderPhaseStatusText,
  renderPhaseWidgetLines,
  SOMA_STATUS_KEY,
} from ${widgetsModule};
import {
  renderIsaChecklistLines,
  type IsaChecklistCriterion,
} from ${checklistModule};

// Cap retained body lines per phase to keep memory + per-delta widget
// serialization bounded over long Algorithm sessions (Sage perf
// important). When the cap is exceeded, the head is dropped and a
// truncation indicator is inserted so the widget shows the run is
// summarized.
const PHASE_BODY_LINE_CAP = 200;
const PHASE_BODY_TRUNCATION_LINE = "… (older lines truncated) …";

// Cap streamed-text inputs and the per-run carry buffer to defend
// against adversarial or malformed model streams that emit a huge
// no-newline fragment (which would otherwise grow run.carry without
// any per-phase cap kicking in — those caps trigger only after a
// newline arrives). Sage R7 security important.
const STREAM_INPUT_MAX_BYTES = 256 * 1024; // 256 KiB per delta/snapshot
const CARRY_MAX_BYTES = 64 * 1024;          // 64 KiB unterminated line
const SOMA_ALGORITHM_ENTRY_KIND = "soma-algorithm-run";
const MAX_CHECKPOINTS_PER_RUN = 8;
const RESTORE_ENTRY_SCAN_LIMIT = 16;
const MAX_POLICY_TARGETS = 16;
const INSTALLED_SOMA_HOME = ${installedSomaHome};
const SOMA_CLI_ENTRYPOINT = ${somaCliEntrypoint};

interface SeenPhase {
  readonly marker: PhaseMarker;
  body: string[];
}

interface RunState {
  readonly runId: string;
  /** Carry-over of the last partial line — joined onto the next delta. */
  carry: string;
  /**
   * Total complete lines ingested so far. Used as the stable lineIndex
   * for new markers so cross-render references stay valid even though
   * we never hold the full buffer in memory.
   */
  lineCount: number;
  /**
   * Bytes of the last whole-message snapshot we ingested. Pi.dev may
   * deliver \`message_update\` as a growing snapshot in \`text\`/
   * \`content\` (not a delta), in which case each event includes
   * everything prior. We diff against the previous snapshot length
   * to ingest only the new suffix (Sage R4 perf important).
   */
  lastSnapshotLength: number;
  seenPhases: SeenPhase[];
  /**
   * Direct reference to the currently-active SeenPhase so coalesced
   * repeated markers (Sage R6) correctly attribute subsequent body
   * lines to the reactivated phase, not to the latest-pushed phase
   * (Sage R7 codequality important). Cleared when no phase has been
   * observed yet.
   */
  activePhase?: SeenPhase;
  currentPhase?: AlgorithmPhaseKey;
  isaCriteria: IsaChecklistCriterion[];
}

const runs = new Map<string, RunState>();
const checkpointCounts = new Map<string, number>();

function somaHomePath(): string {
  return INSTALLED_SOMA_HOME;
}

function runSomaLifecycle(event: "algorithm-observed"): void {
  execFile("bun", [SOMA_CLI_ENTRYPOINT, "lifecycle", event, "--soma-home", somaHomePath(), "--substrate", "pi-dev"], {
    encoding: "utf8",
    timeout: 25000,
  }, () => undefined);
}

function hydrateRun(snapshot: unknown): RunState | undefined {
  const s = hydrateAlgorithmRunSnapshot(snapshot);
  if (!s) return undefined;
  const run: RunState = {
    runId: s.runId,
    carry: s.carry,
    lineCount: s.lineCount,
    lastSnapshotLength: s.lastSnapshotLength,
    seenPhases: s.seenPhases as SeenPhase[],
    activePhase: undefined,
    currentPhase: s.currentPhase as AlgorithmPhaseKey | undefined,
    isaCriteria: s.isaCriteria as IsaChecklistCriterion[],
  };
  run.activePhase = run.currentPhase ? run.seenPhases.find((seen) => seen.marker.phase === run.currentPhase) : run.seenPhases.at(-1);
  return run;
}

function isRunComplete(run: RunState): boolean {
  return isAlgorithmRunSnapshotComplete(run);
}

async function checkpointRun(pi: ExtensionAPI, run: RunState, reason: string): Promise<void> {
  if (isRunComplete(run)) return;
  const checkpointCount = checkpointCounts.get(run.runId) ?? 0;
  if (checkpointCount >= MAX_CHECKPOINTS_PER_RUN) return;
  const appendEntry = (pi as unknown as { appendEntry?: (kind: string, payload: AlgorithmRunSnapshot) => Promise<void> | void }).appendEntry;
  if (!appendEntry) return;
  await appendEntry(SOMA_ALGORITHM_ENTRY_KIND, snapshotAlgorithmRunState(run, reason));
  checkpointCounts.set(run.runId, checkpointCount + 1);
}

async function restoreLatestRun(pi: ExtensionAPI, ctx: unknown): Promise<void> {
  const entries = await (pi as unknown as { readEntries?: (kind: string, options?: { limit?: number }) => Promise<unknown[]> | unknown[] })
    .readEntries?.(SOMA_ALGORITHM_ENTRY_KIND, { limit: RESTORE_ENTRY_SCAN_LIMIT });
  if (!Array.isArray(entries) || entries.length === 0) return;
  for (const entry of entries.slice(-RESTORE_ENTRY_SCAN_LIMIT).reverse()) {
    const payload = (entry as { payload?: unknown }).payload ?? entry;
    const run = hydrateRun(payload);
    if (!run || run.seenPhases.length === 0 || isRunComplete(run)) continue;
    runs.set(run.runId, run);
    renderAllPhases(pi, ctx, run);
    return;
  }
}

async function runSomaPolicyCheck(event: unknown, ctx: unknown): Promise<{ block: boolean; reason: string }> {
  const cwd = typeof (ctx as { cwd?: unknown }).cwd === "string" ? (ctx as { cwd: string }).cwd : process.cwd();
  const extraction = extractToolCallPolicyTargets(event, { cwd, maxTargets: MAX_POLICY_TARGETS });
  if (extraction.blockReason) return { block: true, reason: extraction.blockReason };
  if (extraction.targets.length === 0) return { block: false, reason: "" };
  const policyAction = somaPolicyActionForToolAction(extraction.action);
  try {
    const results = await Promise.all(
      extraction.targets.map(async (target) => {
        if (extraction.action === "write") {
          const guard = await checkSomaPolicy({
            somaHome: somaHomePath(),
            substrate: "pi-dev",
            action: "modify",
            cwd,
            destinationPath: target.filePath,
            record: "deny",
          });
          if (guard.decision === "deny") return guard;
        }
        return checkSomaPolicy({
          somaHome: somaHomePath(),
          substrate: "pi-dev",
          action: policyAction,
          cwd,
          destinationPath: target.filePath,
          sourcePath: target.sourcePath,
          content: target.content,
          record: "deny",
        });
      }),
    );
    const denied = results.find((result) => result.decision === "deny");
    if (denied) return { block: true, reason: denied.reason };
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    return { block: true, reason };
  }
  return { block: false, reason: "" };
}

function defaultRunId(): string {
  // One implicit run per pi.dev session for now. Concurrent runs (open
  // Q2) are already supported by the key scheme; the extension just
  // needs a hook to fire \`startRun(explicitRunId)\` — wired in the
  // \`/algorithm\` command below.
  return "default";
}

function ensureRun(runId: string): RunState {
  let run = runs.get(runId);
  if (!run) {
    run = {
      runId,
      carry: "",
      lineCount: 0,
      lastSnapshotLength: 0,
      seenPhases: [],
      activePhase: undefined,
      currentPhase: undefined,
      isaCriteria: [],
    };
    runs.set(runId, run);
  }
  return run;
}

interface UIShape {
  setWidget?: (key: string, lines: string[]) => void;
  setStatus?: (key: string, text: string) => void;
}

function renderPhaseWidget(ui: UIShape, run: RunState, seen: SeenPhase): void {
  const key = phaseWidgetKey({ runId: run.runId, phase: seen.marker.phase, position: seen.marker.position });
  const lines = renderPhaseWidgetLines({
    marker: seen.marker,
    body: seen.body,
    active: run.currentPhase === seen.marker.phase,
  });
  ui.setWidget?.(key, lines);
}

function renderOverview(ui: UIShape, run: RunState): void {
  ui.setWidget?.(
    \`soma-\${run.runId}-overview\`,
    renderPhaseOverviewLines({
      seenPhases: new Set(run.seenPhases.map((s) => s.marker.phase)),
      currentPhase: run.currentPhase,
    }),
  );
}

function renderStatus(ui: UIShape, run: RunState): void {
  // Footer reflects the active phase (not seenPhases[last]) so a
  // coalesced repeated marker correctly drives the status text (Sage
  // R7 codequality).
  if (run.activePhase) {
    ui.setStatus?.(SOMA_STATUS_KEY, renderPhaseStatusText({ marker: run.activePhase.marker }));
  }
}

function renderIsaWidget(ui: UIShape, run: RunState): void {
  ui.setWidget?.(isaCriteriaWidgetKey(run.runId), renderIsaChecklistLines(run.isaCriteria));
}

/**
 * Full re-render — used on phase transitions and ISA criteria updates,
 * or as a one-shot full refresh path (e.g. /reload restore in the
 * deferred AC-8). Walks every seen phase plus overview, status, and
 * the ISA widget.
 */
function renderAllPhases(_pi: ExtensionAPI, ctx: unknown, run: RunState): void {
  const ui = (ctx as { ui?: UIShape }).ui;
  if (!ui) return;
  for (const seen of run.seenPhases) renderPhaseWidget(ui, run, seen);
  renderOverview(ui, run);
  renderIsaWidget(ui, run);
  renderStatus(ui, run);
}

/**
 * Targeted re-render — used on streamed deltas that grew the active
 * phase's body without crossing a marker boundary. Updates only the
 * active phase widget plus footer status (status is cheap and may
 * carry a body-byte counter in the future). Skips overview + ISA
 * widget + every other phase widget, avoiding O(phases) per-delta
 * serialization (Sage R3 perf suggestion).
 *
 * Uses run.activePhase (not seenPhases[length-1]) so coalesced
 * repeated phases attribute correctly (Sage R7 codequality).
 */
function renderActivePhase(_pi: ExtensionAPI, ctx: unknown, run: RunState): void {
  const ui = (ctx as { ui?: UIShape }).ui;
  if (!ui) return;
  if (run.activePhase) renderPhaseWidget(ui, run, run.activePhase);
  renderStatus(ui, run);
}

interface LineDelta {
  changed: boolean;
  phaseAdded: boolean;
}

function processLine(run: RunState, rawLine: string): LineDelta {
  const line = rawLine.replace(/\\s+$/u, "");
  const markers = parseAlgorithmPhaseMarkers(line);
  if (markers.length > 0) {
    const m = markers[0];
    // Coalesce repeated markers by phase key — a long run that
    // re-emits a phase header (e.g. EXECUTE → tool call interlude →
    // EXECUTE again) would otherwise accumulate a new SeenPhase
    // record per repeat, growing memory and the per-transition
    // render work unbounded (Sage R6 perf important). The existing
    // record stays in place and keeps its accumulated body; we
    // re-point activePhase at it so subsequent body lines correctly
    // attribute back to the reactivated phase (Sage R7 codequality
    // important — previous body-append used \`seenPhases[length-1]\`
    // which routes to the wrong widget after a coalesce).
    const existing = run.seenPhases.find((s) => s.marker.phase === m.phase);
    if (existing) {
      run.activePhase = existing;
      run.currentPhase = m.phase;
      run.lineCount += 1;
      return { changed: true, phaseAdded: false };
    }
    const stableMarker: PhaseMarker = {
      phase: m.phase,
      position: m.position,
      total: m.total,
      lineIndex: run.lineCount,
      rawLine: m.rawLine,
    };
    const fresh: SeenPhase = { marker: stableMarker, body: [] };
    run.seenPhases.push(fresh);
    run.activePhase = fresh;
    run.currentPhase = m.phase;
    run.lineCount += 1;
    return { changed: true, phaseAdded: true };
  }
  const active = run.activePhase;
  if (!active) {
    run.lineCount += 1;
    return { changed: false, phaseAdded: false };
  }
  // Skip leading blank lines on a phase's body; preserve interior
  // blanks but never emit a trailing blank.
  if (active.body.length === 0 && line === "") {
    run.lineCount += 1;
    return { changed: false, phaseAdded: false };
  }
  active.body.push(line);
  // Cap per-phase body to PHASE_BODY_LINE_CAP. When breached, drop
  // the head and insert a one-line truncation indicator at the
  // front (Sage R2 perf important: unbounded growth → bounded memory
  // and per-delta widget serialization).
  if (active.body.length > PHASE_BODY_LINE_CAP) {
    const overflow = active.body.length - PHASE_BODY_LINE_CAP;
    active.body.splice(0, overflow);
    if (active.body[0] !== PHASE_BODY_TRUNCATION_LINE) {
      active.body[0] = PHASE_BODY_TRUNCATION_LINE;
    }
  }
  run.lineCount += 1;
  return { changed: true, phaseAdded: false };
}

/**
 * Incremental ingest — splits the new delta into complete lines and
 * processes one line at a time. New phase markers append a SeenPhase
 * record; non-marker lines go into the active phase's body buffer.
 *
 * Cost is O(deltaLines), not O(totalBufferLines), so long Algorithm
 * runs don't cumulatively re-parse the full transcript on every
 * streamed fragment (Sage R1 perf finding).
 *
 * Per-phase body is capped at PHASE_BODY_LINE_CAP lines so retained
 * memory + widget render work stay bounded over long sessions (Sage
 * R2 perf finding).
 *
 * Returns \`changed = true\` when either a new marker appeared OR the
 * active phase's body grew, so the caller knows when a render is
 * worth pushing.
 *
 * \`opts.flush\` processes \`run.carry\` as a complete final line. Set
 * for whole-message \`text\`/\`content\` payloads that arrive without a
 * trailing newline (Sage R2 CodeQuality important: deltas-only loop
 * dropped the final line when pi.dev delivered a full message).
 */
function ingestStream(text: string, runId: string, opts: { flush?: boolean } = {}): { run: RunState; changed: boolean; phaseAdded: boolean } {
  const run = ensureRun(runId);
  if (!text && !opts.flush) return { run, changed: false, phaseAdded: false };

  // Join carry-over with the new chunk, then split on line boundaries.
  // The final element is the new carry (may be partial; no trailing \\n).
  const combined = run.carry + text;
  const parts = combined.split(/\\r?\\n/);
  run.carry = parts.pop() ?? "";
  // Cap carry size: even a well-behaved client could end up with a
  // long line; an adversarial one could send a single fragment with
  // no newlines forever. Drop the head, keep the tail — that's the
  // text most likely to contain a marker as more bytes arrive (Sage
  // R7 security important).
  if (run.carry.length > CARRY_MAX_BYTES) {
    run.carry = run.carry.slice(run.carry.length - CARRY_MAX_BYTES);
  }

  let changed = false;
  let phaseAdded = false;
  for (const rawLine of parts) {
    const d = processLine(run, rawLine);
    if (d.changed) changed = true;
    if (d.phaseAdded) phaseAdded = true;
  }

  if (opts.flush && run.carry.length > 0) {
    const d = processLine(run, run.carry);
    if (d.changed) changed = true;
    if (d.phaseAdded) phaseAdded = true;
    run.carry = "";
  }

  return { run, changed, phaseAdded };
}

// Exported for unit/integration testing inside Soma (the pi.dev test
// harness can import the extension as ESM and drive ingestStream
// directly). Pi.dev itself only consumes the default export.
export const __internals = { ensureRun, ingestStream, renderAllPhases, renderActivePhase, runs };

export default function (pi: ExtensionAPI): void {
  // Local helper — pi.dev's ExtensionAPI is typed as readonly in the
  // ambient .d.ts, but the runtime exposes an \`on(event, handler)\`
  // method. One cast here, called from every hook registration below
  // — keeps the largest unit scannable (Sage R9 maintainability
  // suggestion).
  type Handler = (event: unknown, ctx: unknown) => void | Promise<void>;
  const on = (event: string, handler: Handler): void => {
    (pi as unknown as { on?: (event: string, handler: Handler) => void }).on?.(event, handler);
  };

  on("session_start", async (_event, ctx) => {
    await restoreLatestRun(pi, ctx);
  });

  // AC-1: slash command \`/algorithm <prompt>\` — steers the session
  // into an Algorithm run with the canonical primer prepended.
  pi.registerCommand("algorithm", {
    description: "Start a Soma Algorithm run rendered as persistent widgets",
    handler: async (args, ctx) => {
      const prompt = (args ?? "").trim();
      if (!prompt) {
        (ctx as { ui?: { notify?: (msg: string, level: string) => void } }).ui?.notify?.(
          "Usage: /algorithm <prompt>",
          "error",
        );
        return;
      }
      // Reset implicit run state when a new run is steered.
      runs.delete(defaultRunId());
      // Primer emits the EXACT marker shape the parser recognizes:
      //   ━━━ <emoji> <NAME> ━━━ <n>/<m>
      // Otherwise the slash command produces output the parser ignores
      // and /algorithm does not drive phase widgets (Sage CodeQuality
      // important).
      const primer = [
        "Enter the Soma Algorithm. Emit canonical phase headers verbatim:",
        ...ALGORITHM_PHASES.map(
          (d) => \`  ━━━ \${d.emoji} \${d.name} ━━━ \${d.position}/\${d.total}\`,
        ),
        "",
        "User prompt:",
        prompt,
      ].join("\\n");
      await (pi as unknown as { sendUserMessage?: (text: string, opts?: unknown) => Promise<void> }).sendUserMessage?.(
        primer,
        { deliverAs: "steer" },
      );
    },
  });

  // AC-4/AC-6: phase transitions AND in-phase body growth update
  // widgets + footer on every streamed text fragment. Re-render on
  // any change, not only on phase advancement, so the active widget
  // reflects streamed body content as it arrives (Sage R1 CodeQuality
  // suggestion).
  //
  // Targeted re-renders: when a delta only grew the active phase's
  // body (no new marker), re-render only the active phase widget +
  // footer status. Full re-render is reserved for phase transitions
  // (which need overview + the new phase's widget) and ISA updates
  // (which need the criteria widget). Avoids O(phases) per-delta
  // widget serialization (Sage R3 perf suggestion).
  on("message_update", (event, ctx) => {
      const e = event as { delta?: unknown; text?: unknown; content?: unknown };
      // Distinguish a streamed delta (newline-terminated fragment) from
      // a whole-message snapshot (text/content). Whole-message
      // snapshots must be flushed so the final unterminated line is
      // ingested (Sage R2 CodeQuality important).
      const isDelta = typeof e.delta === "string";
      const raw = String(e.delta ?? e.text ?? e.content ?? "");
      if (!raw) return;
      const run = ensureRun(defaultRunId());
      // Snapshot mode: pi.dev may deliver text/content as cumulative
      // snapshots — each event includes all prior text plus the new
      // suffix. Slice to the unconsumed suffix so we don't reparse the
      // whole transcript on every event (Sage R4 perf important).
      // Deltas pass through unchanged.
      //
      // IMPORTANT: the byte cap (STREAM_INPUT_MAX_BYTES, Sage R7
      // security) is applied AFTER computing the unconsumed suffix,
      // not against the raw snapshot. Otherwise the cursor
      // (lastSnapshotLength) drifts off the real snapshot length and
      // later updates would slice the wrong window or false-trigger
      // the snapshot-shrank reset (Sage R8 CodeQuality important).
      let chunk = raw;
      if (!isDelta) {
        if (raw.length < run.lastSnapshotLength) {
          // Snapshot shrank — new message started. Reset cursor AND
          // clear any unterminated carry from the previous snapshot;
          // joining a stale carry onto the new message would corrupt
          // the first parsed line (Sage R6 CodeQuality important).
          run.lastSnapshotLength = 0;
          run.carry = "";
        }
        chunk = raw.slice(run.lastSnapshotLength);
        // Cursor tracks the original snapshot length so subsequent
        // events compute the right suffix even when the snapshot
        // exceeds the byte cap.
        run.lastSnapshotLength = raw.length;
      }
      // Defense in depth against a single huge no-newline fragment
      // (Sage R7 security important). Cap the chunk we actually
      // ingest. For deltas, drop overflow head-side. For snapshots,
      // slice from the tail so we keep the most recent content.
      if (chunk.length > STREAM_INPUT_MAX_BYTES) {
        chunk = isDelta ? chunk.slice(0, STREAM_INPUT_MAX_BYTES) : chunk.slice(chunk.length - STREAM_INPUT_MAX_BYTES);
      }
      if (!chunk) return;
      // Do NOT flush snapshot mode: the trailing line of a cumulative
      // snapshot may still be growing — the next event will deliver
      // more of it. Flushing here would split a still-incomplete
      // marker or body line into fragments that never parse (Sage R5
      // CodeQuality important). True deltas also don't need a flush:
      // they're newline-terminated fragments by definition, and any
      // partial trailing line is correctly held in run.carry until
      // the next delta arrives.
      const { changed, phaseAdded } = ingestStream(chunk, defaultRunId());
      if (!changed) return;
      if (phaseAdded) renderAllPhases(pi, ctx, run);
      else renderActivePhase(pi, ctx, run);
    });

  // Flush the carry on terminal events so any final unterminated line
  // (which we deliberately held during streaming — see message_update
  // comment about Sage R5 partial-line flush) gets parsed before the
  // session/agent fully ends.
  for (const terminal of ["agent_end", "message_end", "session_before_compact", "session_shutdown"] as const) {
    on(terminal, async (_event, ctx) => {
      const run = ensureRun(defaultRunId());
      const { changed, phaseAdded } = ingestStream("", defaultRunId(), { flush: true });
      if (changed) {
        if (phaseAdded) renderAllPhases(pi, ctx, run);
        else renderActivePhase(pi, ctx, run);
      }
      if (terminal === "session_before_compact") {
        await checkpointRun(pi, run, "session_before_compact");
      }
      runSomaLifecycle("algorithm-observed");
    });
  }

  on("tool_call", async (event, ctx) => {
    const run = ensureRun(defaultRunId());
    if (run.currentPhase !== "execute") return undefined;
    const policy = await runSomaPolicyCheck(event, ctx);
    if (policy.block) return { block: true, reason: policy.reason };
    return undefined;
  });

  // AC-5: ISA criteria widget updates whenever the soma \`isa_update\`
  // tool returns. Minimal parsing for this PR — full criteria diff
  // landing in the deferred PR alongside e2e wiring.
  on("tool_result", (event, ctx) => {
    const toolName = String((event as { toolName?: unknown }).toolName ?? "").toLowerCase();
    if (toolName !== "isa_update" && toolName !== "soma_isa_update") return;
    const result = (event as { result?: unknown }).result;
    // Validate the untyped boundary: the tool result is foreign
    // data from the model side of the pi.dev runtime. A malformed
    // or adversarial payload with non-array criteria (or with
    // criterion fields of the wrong type) would crash the checklist
    // renderer and DoS the extension (Sage R3 security important).
    // Coerce to a typed array, dropping malformed entries silently.
    const criteria = sanitizeIsaCriteria(result);
    if (!criteria) return;
    const run = ensureRun(defaultRunId());
    run.isaCriteria = criteria;
    renderAllPhases(pi, ctx, run);
  });
}

// Sage R4 security suggestion: cap criteria count + per-field length
// before pushing. A malformed/adversarial isa_update result could
// otherwise flood memory + widget serialization with very large arrays
// or strings.
const ISA_CRITERIA_MAX_COUNT = 200;
const ISA_CRITERIA_FIELD_MAX_LENGTH = 256;

function clip(s: string): string {
  if (s.length <= ISA_CRITERIA_FIELD_MAX_LENGTH) return s;
  return s.slice(0, ISA_CRITERIA_FIELD_MAX_LENGTH - 1) + "…";
}

function sanitizeIsaCriteria(result: unknown): IsaChecklistCriterion[] | undefined {
  if (!result || typeof result !== "object") return undefined;
  const raw = (result as { criteria?: unknown }).criteria;
  if (!Array.isArray(raw)) return undefined;
  const out: IsaChecklistCriterion[] = [];
  for (const entry of raw) {
    if (out.length >= ISA_CRITERIA_MAX_COUNT) break;
    if (!entry || typeof entry !== "object") continue;
    const e = entry as { id?: unknown; title?: unknown; status?: unknown };
    if (typeof e.id !== "string" || typeof e.title !== "string" || typeof e.status !== "string") continue;
    out.push({ id: clip(e.id), title: clip(e.title), status: clip(e.status) });
  }
  return out;
}
`;
}
