/**
 * Render the soma-algorithm pi.dev extension source as a TypeScript
 * string. Soma-issue-43 minimal-correct slice (AC-1, AC-4, AC-5, AC-6
 * code paths; AC-2 wiring lives in adapter.ts + install.ts).
 *
 * Mirrors the `renderPathGuardExtension` pattern (`path-guard.ts`):
 *
 *   - Returned string is written verbatim to `~/.pi/agent/extensions/
 *     soma-algorithm.ts` by the pi-dev home projection.
 *   - Pi.dev hot-reloads `.ts`, so no build step at install time.
 *   - Pure-logic helpers (`phase-parser`, `widget-renderers`,
 *     `isa-checklist`) are imported via a `file://` URL into the
 *     compiled Soma repo so the runtime stays in lockstep with the
 *     parser unit tests — no string-bundled duplicate logic to drift.
 *
 * Open-question resolutions baked into this file (see issue body):
 *   Q1 (TS vs JS):       ship `.ts`.
 *   Q2 (concurrent runs): widget keys include `runId`.
 *   Q3 (version probe):   DEFERRED — TODO in the extension header.
 *   Q4 (other substrates): pi.dev only.
 *
 * Out of scope (deferred ACs filed as follow-up issue):
 *   AC-7  tool_call blocking via soma policy check
 *   AC-8  /reload widget restoration
 *   AC-9  session_compact checkpoint
 *   AC-10 install-time version refusal
 *   AC-11 compat matrix doc
 *   AC-12 live e2e against pi.dev
 *
 * Pi.dev `ExtensionAPI` is NOT a Soma build-time dep. The extension
 * imports the type from `@mariozechner/pi-coding-agent` directly — that
 * package resolves at pi.dev runtime where the extension actually
 * executes. Soma's package.json is unchanged.
 */

import { join } from "node:path";
import { pathToFileURL } from "node:url";

export interface RenderSomaAlgorithmExtensionOptions {
  /**
   * Override the runtime module specifier used by the extension to
   * import the pure-logic helpers. Defaults to the absolute `file://`
   * URL of the Soma repo's `phase-parser.ts`/`widget-renderers.ts`/
   * `isa-checklist.ts`. Override is only useful in unit tests.
   */
  readonly runtimeModuleDir?: string;
}

function defaultRuntimeModuleDir(): string {
  return pathToFileURL(join(import.meta.dir, "/")).href;
}

/**
 * Render the soma-algorithm extension TypeScript source.
 *
 * The returned string is exactly what gets written to disk at
 * `~/.pi/agent/extensions/soma-algorithm.ts`.
 */
export function renderSomaAlgorithmExtension(options: RenderSomaAlgorithmExtensionOptions = {}): string {
  const runtimeDir = options.runtimeModuleDir ?? defaultRuntimeModuleDir();
  // Trailing slash is preserved by pathToFileURL when the input is a dir.
  // Helper module specifiers — each helper lives in its own file in
  // src/adapters/pi-dev/extensions/.
  const parserModule = JSON.stringify(`${runtimeDir}phase-parser.ts`);
  const widgetsModule = JSON.stringify(`${runtimeDir}widget-renderers.ts`);
  const checklistModule = JSON.stringify(`${runtimeDir}isa-checklist.ts`);

  return `// soma-algorithm pi.dev extension — generated by Soma. Do not edit by hand.
//
// Renders an active Soma Algorithm run as persistent, per-phase widgets:
//
//   ▸ soma-<runId>-phase-1-observe   ...   soma-<runId>-phase-7-summary
//   ▸ soma-<runId>-isa-criteria
//   ▸ status slot "soma" = "Phase N/7 — NAME"
//
// TODO(#43 follow-up): probe pi-dev version + refuse-install on old hosts
// (AC-10). For now this extension assumes pi-dev >= the release that
// landed \`ctx.ui.setWidget\` + \`ctx.ui.setStatus\` + the \`message_update\`
// event. If those primitives are absent the extension no-ops safely
// (every call site is optional-chained).

import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import {
  ALGORITHM_PHASES,
  latestAlgorithmPhaseMarker,
  parseAlgorithmPhaseMarkers,
  type AlgorithmPhaseKey,
  type PhaseMarker,
} from ${parserModule};
import {
  capabilitiesWidgetKey,
  isaCriteriaWidgetKey,
  phaseWidgetKey,
  renderPhaseOverviewLines,
  renderPhaseStatusText,
  renderPhaseWidgetLines,
  SOMA_STATUS_KEY,
} from ${widgetsModule};
import {
  renderIsaChecklistLines,
  type IsaChecklistCriterion,
} from ${checklistModule};

interface RunState {
  readonly runId: string;
  buffer: string;
  seenMarkers: PhaseMarker[];
  currentPhase?: AlgorithmPhaseKey;
  isaCriteria: IsaChecklistCriterion[];
}

const runs = new Map<string, RunState>();

function defaultRunId(): string {
  // One implicit run per pi.dev session for now. Concurrent runs (open
  // Q2) are already supported by the key scheme; the extension just
  // needs a hook to fire \`startRun(explicitRunId)\` — wired in the
  // \`/algorithm\` command below.
  return "default";
}

function ensureRun(runId: string): RunState {
  let run = runs.get(runId);
  if (!run) {
    run = { runId, buffer: "", seenMarkers: [], currentPhase: undefined, isaCriteria: [] };
    runs.set(runId, run);
  }
  return run;
}

function bodyForPhase(run: RunState, marker: PhaseMarker): string[] {
  // Slice the run buffer between this marker line and the next marker
  // line (or end of stream). Returned lines are trimmed of trailing
  // whitespace; leading/trailing blank lines stripped.
  const lines = run.buffer.split(/\\r?\\n/);
  const start = marker.lineIndex + 1;
  let end = lines.length;
  for (const next of run.seenMarkers) {
    if (next.lineIndex > marker.lineIndex && next.lineIndex < end) end = next.lineIndex;
  }
  const slice: string[] = [];
  for (let i = start; i < end; i += 1) slice.push(lines[i].replace(/\\s+$/u, ""));
  while (slice.length > 0 && slice[0] === "") slice.shift();
  while (slice.length > 0 && slice[slice.length - 1] === "") slice.pop();
  return slice;
}

function renderAllPhases(pi: ExtensionAPI, ctx: unknown, run: RunState): void {
  const ui = (ctx as { ui?: { setWidget?: (key: string, lines: string[]) => void; setStatus?: (key: string, text: string) => void } }).ui;
  if (!ui) return;

  // AC-4: populate one widget per phase that has been observed; prior
  // widgets remain set (pi.dev preserves widget content across updates
  // unless explicitly overwritten or cleared).
  for (const marker of run.seenMarkers) {
    const key = phaseWidgetKey({ runId: run.runId, phase: marker.phase, position: marker.position });
    const lines = renderPhaseWidgetLines({
      marker,
      body: bodyForPhase(run, marker),
      active: run.currentPhase === marker.phase,
    });
    ui.setWidget?.(key, lines);
  }

  // Overview widget — single per-run dashboard of all 8 phase descriptors.
  ui.setWidget?.(
    \`soma-\${run.runId}-overview\`,
    renderPhaseOverviewLines({
      seenPhases: new Set(run.seenMarkers.map((m) => m.phase)),
      currentPhase: run.currentPhase,
    }),
  );

  // AC-5: ISA criteria widget — always rendered, even when empty.
  ui.setWidget?.(isaCriteriaWidgetKey(run.runId), renderIsaChecklistLines(run.isaCriteria));

  // AC-6: footer status.
  const latest = run.seenMarkers[run.seenMarkers.length - 1];
  if (latest) ui.setStatus?.(SOMA_STATUS_KEY, renderPhaseStatusText({ marker: latest }));
}

function ingestStream(text: string, runId: string): { run: RunState; advanced: boolean } {
  const run = ensureRun(runId);
  run.buffer += text;
  const markers = parseAlgorithmPhaseMarkers(run.buffer);
  const latest = latestAlgorithmPhaseMarker(run.buffer);
  const advanced = markers.length !== run.seenMarkers.length;
  run.seenMarkers = markers;
  run.currentPhase = latest?.phase;
  return { run, advanced };
}

// Exported for unit/integration testing inside Soma (the pi.dev test
// harness can import the extension as ESM and drive ingestStream
// directly). Pi.dev itself only consumes the default export.
export const __internals = { ensureRun, ingestStream, renderAllPhases, runs };

export default function (pi: ExtensionAPI): void {
  // AC-1: slash command \`/algorithm <prompt>\` — steers the session
  // into an Algorithm run with the canonical primer prepended.
  pi.registerCommand("algorithm", {
    description: "Start a Soma Algorithm run rendered as persistent widgets",
    handler: async (args, ctx) => {
      const prompt = (args ?? "").trim();
      if (!prompt) {
        (ctx as { ui?: { notify?: (msg: string, level: string) => void } }).ui?.notify?.(
          "Usage: /algorithm <prompt>",
          "error",
        );
        return;
      }
      // Reset implicit run state when a new run is steered.
      runs.delete(defaultRunId());
      const primer = [
        "Enter the Soma Algorithm. Emit canonical phase headers verbatim:",
        ...ALGORITHM_PHASES.map((d) => \`  \${d.emoji} \${d.name} \${d.position}/\${d.total}\`),
        "",
        "User prompt:",
        prompt,
      ].join("\\n");
      await (pi as unknown as { sendUserMessage?: (text: string, opts?: unknown) => Promise<void> }).sendUserMessage?.(
        primer,
        { deliverAs: "steer" },
      );
    },
  });

  // AC-4/AC-6: phase transitions update widgets + footer on every
  // streamed text fragment.
  (pi as unknown as { on?: (event: string, handler: (event: unknown, ctx: unknown) => void | Promise<void>) => void }).on?.(
    "message_update",
    (event, ctx) => {
      const text = String(
        (event as { delta?: unknown; text?: unknown; content?: unknown }).delta ??
          (event as { text?: unknown }).text ??
          (event as { content?: unknown }).content ??
          "",
      );
      if (!text) return;
      const { run, advanced } = ingestStream(text, defaultRunId());
      if (advanced) renderAllPhases(pi, ctx, run);
    },
  );

  // AC-5: ISA criteria widget updates whenever the soma \`isa_update\`
  // tool returns. Minimal parsing for this PR — full criteria diff
  // landing in the deferred PR alongside e2e wiring.
  (pi as unknown as { on?: (event: string, handler: (event: unknown, ctx: unknown) => void | Promise<void>) => void }).on?.(
    "tool_result",
    (event, ctx) => {
      const toolName = String((event as { toolName?: unknown }).toolName ?? "").toLowerCase();
      if (toolName !== "isa_update" && toolName !== "soma_isa_update") return;
      const result = (event as { result?: { criteria?: IsaChecklistCriterion[] } }).result;
      if (!result?.criteria) return;
      const run = ensureRun(defaultRunId());
      run.isaCriteria = result.criteria;
      renderAllPhases(pi, ctx, run);
    },
  );
}
`;
}
