#!/usr/bin/env bun
/**
 * Regenerates `src/bundled-skill-files.generated.ts`: one bun text import per
 * file under `src/skills`, so bundled skill content is inlined into a
 * `bun build --compile` binary instead of read from a path derived from
 * `import.meta`, which a compiled binary resolves into the empty `/$bunfs`
 * root (orienteer node #612).
 *
 * Run after adding, removing or renaming any file under `src/skills`:
 *
 *     bun run generate-bundled-skill-files
 *
 * `test/repo-path-compile.test.ts` fails while the committed module is stale.
 */
import { readdirSync, writeFileSync } from "node:fs";
import { join, relative, resolve, sep } from "node:path";

const REPO_ROOT = resolve(import.meta.dir, "..");
export const BUNDLED_SKILL_FILES_MODULE = join(REPO_ROOT, "src", "bundled-skill-files.generated.ts");
const SKILLS_ROOT = join(REPO_ROOT, "src", "skills");

export function walk(root: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const path = join(root, entry.name);
    if (entry.isDirectory()) out.push(...walk(path));
    else if (entry.isFile()) out.push(path);
  }
  return out;
}

/** Posix paths of every file under `src/skills/<skill>/`, sorted by code unit. */
export function bundledSkillFilePaths(skillsRoot = SKILLS_ROOT): string[] {
  return walk(skillsRoot)
    .map((path) => relative(skillsRoot, path).split(sep).join("/"))
    // A loose file directly under src/skills belongs to no skill.
    .filter((path) => path.includes("/"))
    .sort();
}

export function renderBundledSkillFilesModule(skillsRoot = SKILLS_ROOT): string {
  const paths = bundledSkillFilePaths(skillsRoot);
  const imports = paths.map((path, index) => `import file${index} from ${JSON.stringify(`./skills/${path}`)} with { type: "text" };`);
  const entries = paths.map((path, index) => `  ${JSON.stringify(path)}: file${index},`);
  return [
    "// GENERATED by scripts/generate-bundled-skill-files.ts from src/skills. Do not edit.",
    "// Regenerate with `bun run generate-bundled-skill-files`.",
    "//",
    "// Only ever loaded through a dynamic import in src/bundled-skill-source.ts, so the",
    "// skill text is read when a skill is installed, not on every invocation.",
    ...imports,
    "",
    "/** Every bundled skill file, keyed by its posix path relative to `src/skills`. */",
    "export const BUNDLED_SKILL_FILES: Readonly<Record<string, string>> = {",
    ...entries,
    "};",
    "",
  ].join("\n");
}

if (import.meta.main) {
  writeFileSync(BUNDLED_SKILL_FILES_MODULE, renderBundledSkillFilesModule());
  console.log(`wrote ${relative(REPO_ROOT, BUNDLED_SKILL_FILES_MODULE)}`);
}
