// GENERATED by scripts/generate-bundled-skill-files.ts from src/skills. Do not edit.
// Regenerate with `bun run generate-bundled-skill-files`.
//
// Only ever loaded through a dynamic import in src/bundled-skill-source.ts, so the
// skill text is read when a skill is installed, not on every invocation.
import file0 from "./skills/Memory/SKILL.md" with { type: "text" };
import file1 from "./skills/Memory/Workflows/Audit.md" with { type: "text" };
import file2 from "./skills/Memory/Workflows/Consolidate.md" with { type: "text" };
import file3 from "./skills/Memory/Workflows/Recall.md" with { type: "text" };
import file4 from "./skills/Memory/Workflows/Remember.md" with { type: "text" };
import file5 from "./skills/VSA/Examples/canonical-vsa.md" with { type: "text" };
import file6 from "./skills/VSA/Examples/e1-minimal.md" with { type: "text" };
import file7 from "./skills/VSA/Examples/e2-backup-verify.md" with { type: "text" };
import file8 from "./skills/VSA/Examples/e2-rotate-credential.md" with { type: "text" };
import file9 from "./skills/VSA/Examples/e3-essay.md" with { type: "text" };
import file10 from "./skills/VSA/Examples/e3-help-redesign.md" with { type: "text" };
import file11 from "./skills/VSA/Examples/e3-project.md" with { type: "text" };
import file12 from "./skills/VSA/Examples/e4-api-migration.md" with { type: "text" };
import file13 from "./skills/VSA/Examples/e4-brand-identity.md" with { type: "text" };
import file14 from "./skills/VSA/Examples/e5-album.md" with { type: "text" };
import file15 from "./skills/VSA/Examples/e5-desktop-app.md" with { type: "text" };
import file16 from "./skills/VSA/Examples/e5-enterprise.md" with { type: "text" };
import file17 from "./skills/VSA/SKILL.md" with { type: "text" };
import file18 from "./skills/VSA/Workflows/Append.md" with { type: "text" };
import file19 from "./skills/VSA/Workflows/CheckCompleteness.md" with { type: "text" };
import file20 from "./skills/VSA/Workflows/Interview.md" with { type: "text" };
import file21 from "./skills/VSA/Workflows/Reconcile.md" with { type: "text" };
import file22 from "./skills/VSA/Workflows/Scaffold.md" with { type: "text" };
import file23 from "./skills/VSA/Workflows/Seed.md" with { type: "text" };
import file24 from "./skills/VSA/references/examples.md" with { type: "text" };
import file25 from "./skills/VSA/references/format.md" with { type: "text" };
import file26 from "./skills/VSA/references/gotchas.md" with { type: "text" };
import file27 from "./skills/migrate-pai-purpose/SKILL.md" with { type: "text" };
import file28 from "./skills/orienteer/SKILL.md" with { type: "text" };
import file29 from "./skills/orienteer/Workflows/ChartTheMap.md" with { type: "text" };
import file30 from "./skills/orienteer/Workflows/WalkTheMap.md" with { type: "text" };
import file31 from "./skills/orienteer/references/build-brief.md" with { type: "text" };
import file32 from "./skills/orienteer/references/closing.md" with { type: "text" };
import file33 from "./skills/orienteer/references/fog.md" with { type: "text" };
import file34 from "./skills/orienteer/references/map.md" with { type: "text" };
import file35 from "./skills/orienteer/references/walker.md" with { type: "text" };
import file36 from "./skills/the-algorithm/SKILL.md" with { type: "text" };
import file37 from "./skills/the-algorithm/Workflows/RunAlgorithm.md" with { type: "text" };
import file38 from "./skills/the-algorithm/references/algorithm.md" with { type: "text" };
import file39 from "./skills/the-algorithm/references/capabilities.md" with { type: "text" };
import file40 from "./skills/the-algorithm/references/eval-guide.md" with { type: "text" };
import file41 from "./skills/the-algorithm/references/ideate-loop.md" with { type: "text" };
import file42 from "./skills/the-algorithm/references/mode-detection.md" with { type: "text" };
import file43 from "./skills/the-algorithm/references/optimize-loop.md" with { type: "text" };
import file44 from "./skills/the-algorithm/references/parameter-schema.md" with { type: "text" };
import file45 from "./skills/the-algorithm/references/target-types.md" with { type: "text" };

/** Every bundled skill file, keyed by its posix path relative to `src/skills`. */
export const BUNDLED_SKILL_FILES: Readonly<Record<string, string>> = {
  "Memory/SKILL.md": file0,
  "Memory/Workflows/Audit.md": file1,
  "Memory/Workflows/Consolidate.md": file2,
  "Memory/Workflows/Recall.md": file3,
  "Memory/Workflows/Remember.md": file4,
  "VSA/Examples/canonical-vsa.md": file5,
  "VSA/Examples/e1-minimal.md": file6,
  "VSA/Examples/e2-backup-verify.md": file7,
  "VSA/Examples/e2-rotate-credential.md": file8,
  "VSA/Examples/e3-essay.md": file9,
  "VSA/Examples/e3-help-redesign.md": file10,
  "VSA/Examples/e3-project.md": file11,
  "VSA/Examples/e4-api-migration.md": file12,
  "VSA/Examples/e4-brand-identity.md": file13,
  "VSA/Examples/e5-album.md": file14,
  "VSA/Examples/e5-desktop-app.md": file15,
  "VSA/Examples/e5-enterprise.md": file16,
  "VSA/SKILL.md": file17,
  "VSA/Workflows/Append.md": file18,
  "VSA/Workflows/CheckCompleteness.md": file19,
  "VSA/Workflows/Interview.md": file20,
  "VSA/Workflows/Reconcile.md": file21,
  "VSA/Workflows/Scaffold.md": file22,
  "VSA/Workflows/Seed.md": file23,
  "VSA/references/examples.md": file24,
  "VSA/references/format.md": file25,
  "VSA/references/gotchas.md": file26,
  "migrate-pai-purpose/SKILL.md": file27,
  "orienteer/SKILL.md": file28,
  "orienteer/Workflows/ChartTheMap.md": file29,
  "orienteer/Workflows/WalkTheMap.md": file30,
  "orienteer/references/build-brief.md": file31,
  "orienteer/references/closing.md": file32,
  "orienteer/references/fog.md": file33,
  "orienteer/references/map.md": file34,
  "orienteer/references/walker.md": file35,
  "the-algorithm/SKILL.md": file36,
  "the-algorithm/Workflows/RunAlgorithm.md": file37,
  "the-algorithm/references/algorithm.md": file38,
  "the-algorithm/references/capabilities.md": file39,
  "the-algorithm/references/eval-guide.md": file40,
  "the-algorithm/references/ideate-loop.md": file41,
  "the-algorithm/references/mode-detection.md": file42,
  "the-algorithm/references/optimize-loop.md": file43,
  "the-algorithm/references/parameter-schema.md": file44,
  "the-algorithm/references/target-types.md": file45,
};
